/* Expanded curated discovery catalogue for v0.2. Broad enough to roam, still hand-tagged. */
FILMS.push(
  // 1920s–1950s: fill the early decades with films that still connect to the app's taste logic
  F('The Cabinet of Dr. Caligari',1920,'Robert Wiene',['1920s','dream','macabre','esoteric','liminal'],'painted nightmare geometry','🌀',4,3),
  F('Nosferatu',1922,'F. W. Murnau',['1920s','macabre','horror','liminal'],'plague-shadow gothic dread','🦇',4,4),
  F('Häxan',1922,'Benjamin Christensen',['1920s','macabre','esoteric','docs-weird','underground'],'witchcraft lecture becomes fever dream','🜏',5,3),
  F('Sherlock Jr.',1924,'Buster Keaton',['1920s','playful','dream','kinetic'],'cinema folds into slapstick physics','🎞',4,4),
  F('The Last Laugh',1924,'F. W. Murnau',['1920s','emotional','stylish'],'status collapse without words','🧥',3,4),
  F('The General',1926,'Buster Keaton',['1920s','kinetic','playful','rocket-fuel'],'locomotive stunt machine','🚂',3,4),
  F('Metropolis',1927,'Fritz Lang',['1920s','cyber','philosophical','liminal','esoteric'],'industrial future as cathedral','⚙',5,4),
  F('The Passion of Joan of Arc',1928,'Carl Theodor Dreyer',['1920s','emotional','unwatchable','philosophical'],'a face under spiritual siege','🔥',5,4),
  F('Un Chien Andalou',1929,'Luis Buñuel',['1920s','dream','brainfuck','underground'],'surrealism with a razor blade','👁',5,3),
  F('Man with a Movie Camera',1929,'Dziga Vertov',['1920s','kinetic','documentary','experimental'],'the city discovers montage','📹',5,4),
  F('M',1931,'Fritz Lang',['1930s','dark','crime','macabre'],'a city hunts its nightmare','🎈',4,4),
  F('Vampyr',1932,'Carl Theodor Dreyer',['1930s','dream','horror','liminal'],'ghost-light drifting through dread','🕯',5,3),
  F('Freaks',1932,'Tod Browning',['1930s','underground','macabre','tender-weirdos'],'outsiders answer cruelty with ritual','🎪',5,4),
  F('Zero for Conduct',1933,'Jean Vigo',['1930s','counterculture','playful','kinetic'],'school revolt as pillow-feather uprising','🪶',4,3),
  F('L’Atalante',1934,'Jean Vigo',['1930s','romantic','dream','tender'],'marriage drifting downriver','🌫',4,4),
  F('Bride of Frankenstein',1935,'James Whale',['1930s','horror','campy','tender-weirdos','macabre'],'monsters discover loneliness','⚡',4,5),
  F('Modern Times',1936,'Charlie Chaplin',['1930s','playful','counterculture','kinetic'],'human body versus machine rhythm','⚙',4,5),
  F('The Rules of the Game',1939,'Jean Renoir',['1930s','dark','playful','social'],'society dances toward collapse','🥂',3,4),
  F('Rebecca',1940,'Alfred Hitchcock',['1940s','romantic','macabre','liminal'],'a marriage haunted by an absent woman','🕯',4,5),
  F('The Great Dictator',1940,'Charlie Chaplin',['1940s','counterculture','playful','political'],'slapstick points at tyranny','🌍',3,5),
  F('Cat People',1942,'Jacques Tourneur',['1940s','horror','psychosexual','liminal'],'desire prowls in shadow','🐈',4,4),
  F('Meshes of the Afternoon',1943,'Maya Deren',['1940s','dream','underground','liminal','25th-hour'],'domestic space loops into trance','🗝',5,4),
  F('Double Indemnity',1944,'Billy Wilder',['1940s','crime','night-city','psychosexual'],'desire signs an insurance policy','🚬',3,5),
  F('Brief Encounter',1945,'David Lean',['1940s','romantic','tender','nostalgic'],'ordinary life meets impossible love','🚉',3,5),
  F('Beauty and the Beast',1946,'Jean Cocteau',['1940s','dream','romantic','esoteric'],'fairy tale moving like a spell','🕯',5,4),
  F('Out of the Past',1947,'Jacques Tourneur',['1940s','crime','night-city','romantic'],'fatalism in cigarette smoke','🚬',4,4),
  F('The Red Shoes',1948,'Michael Powell, Emeric Pressburger',['1940s','dream','stylish','emotional'],'art becomes an ecstatic trap','🩰',5,5),
  F('The Third Man',1949,'Carol Reed',['1940s','night-city','crime','stylish'],'postwar Vienna tilts sideways','🎡',4,5),
  F('Rashomon',1950,'Akira Kurosawa',['1950s','philosophical','brainfuck','curious'],'truth fractures into testimony','🌧',5,5),
  F('Sunset Boulevard',1950,'Billy Wilder',['1950s','night-city','macabre','stylish'],'Hollywood decay narrates itself','🎬',4,5),
  F('Ace in the Hole',1951,'Billy Wilder',['1950s','dark','media','kinetic'],'a tragedy becomes a business model','📰',4,4),
  F('A Streetcar Named Desire',1951,'Elia Kazan',['1950s','psychosexual','emotional','dark'],'desire and delusion in humid rooms','🚪',3,5),
  F('Ikiru',1952,'Akira Kurosawa',['1950s','philosophical','tender','inspiring'],'a dying man learns how to live','🛝',5,5),
  F('The Wages of Fear',1953,'Henri-Georges Clouzot',['1950s','kinetic','rocket-fuel','dark'],'nitroglycerin turns driving into prayer','🚚',4,4),
  F('Ugetsu',1953,'Kenji Mizoguchi',['1950s','dream','macabre','romantic'],'ambition wanders into ghost country','🌫',5,4),
  F('Rear Window',1954,'Alfred Hitchcock',['1950s','curious','crime','playful'],'voyeurism turns neighbors into cinema','🪟',4,5),
  F('Night of the Hunter',1955,'Charles Laughton',['1950s','dream','macabre','tender'],'childhood flees a preacher-shaped nightmare','🌙',5,5),
  F('The Killing',1956,'Stanley Kubrick',['1950s','crime','kinetic','stylish'],'a heist clicks together then splinters','🎲',4,4),
  F('Paths of Glory',1957,'Stanley Kubrick',['1950s','angry','philosophical','dark'],'military honor exposed as theater','🎖',4,5),
  F('Elevator to the Gallows',1958,'Louis Malle',['1950s','night-city','crime','romantic'],'Miles Davis noir at midnight','🎺',5,4),
  F('Vertigo',1958,'Alfred Hitchcock',['1950s','psychosexual','dream','brainfuck'],'obsession remakes a woman into a ghost','🌀',5,5),
  F('Hiroshima mon amour',1959,'Alain Resnais',['1950s','romantic','philosophical','dream'],'memory and desire overlap like ruins','🌫',5,4),

  // 1960s
  F('Eyes Without a Face',1960,'Georges Franju',['1960s','macabre','dream','horror'],'surgical horror with a porcelain soul','🎭',5,4),
  F('Breathless',1960,'Jean-Luc Godard',['1960s','kinetic','romantic','counterculture'],'coolness breaks continuity rules','🚬',4,4),
  F('La Jetée',1962,'Chris Marker',['1960s','dream','philosophical','brainfuck'],'time travel built from still images','✈',5,4),
  F('Cléo from 5 to 7',1962,'Agnès Varda',['1960s','tender','curious','city'],'two hours of life suddenly becoming visible','🪞',4,5),
  F('The Exterminating Angel',1962,'Luis Buñuel',['1960s','brainfuck','esoteric','dark'],'dinner guests discover they cannot leave','🍽',5,4),
  F('8½',1963,'Federico Fellini',['1960s','dream','philosophical','playful'],'creative paralysis turns into circus','🎪',5,4),
  F('High and Low',1963,'Akira Kurosawa',['1960s','crime','kinetic','philosophical'],'a kidnapping splits a city by class','☎',4,5),
  F('Woman in the Dunes',1964,'Hiroshi Teshigahara',['1960s','liminal','psychosexual','philosophical'],'desire and captivity inside a sand pit','⌛',5,4),
  F('Onibaba',1964,'Kaneto Shindō',['1960s','macabre','psychosexual','horror'],'war hunger burns through reeds','👹',5,4),
  F('Persona',1966,'Ingmar Bergman',['1960s','brainfuck','dream','psychosexual'],'two identities bleed into one frame','🎭',5,5),
  F('Blow-Up',1966,'Michelangelo Antonioni',['1960s','curious','brainfuck','stylish'],'a photograph may contain a murder','📷',4,4),
  F('Daisies',1966,'Věra Chytilová',['1960s','playful','counterculture','experimental'],'two women vandalize good taste','🍰',5,5),
  F('Seconds',1966,'John Frankenheimer',['1960s','brainfuck','dark','philosophical'],'a new identity becomes another prison','🥃',5,4),
  F('The Graduate',1967,'Mike Nichols',['1960s','romantic','counterculture','nostalgic'],'post-college drift in chlorinated sunlight','🏊',3,5),
  F('Point Blank',1967,'John Boorman',['1960s','crime','stylish','dream'],'revenge becomes architectural abstraction','🔫',5,4),
  F('If....',1968,'Lindsay Anderson',['1960s','counterculture','angry','surreal'],'school rebellion escapes into fantasy','🎓',5,4),
  F('Funeral Parade of Roses',1969,'Toshio Matsumoto',['1960s','underground','psychosexual','experimental'],'Tokyo queer nightlife explodes form','🌹',5,4),
  F('The Color of Pomegranates',1969,'Sergei Parajanov',['1960s','esoteric','dream','liminal'],'biography rewritten as iconography','🍎',5,3),

  // 1970s
  F('Wake in Fright',1971,'Ted Kotcheff',['1970s','unwatchable','dark','kinetic'],'masculinity bakes in outback heat','🍺',4,3),
  F('The French Connection',1971,'William Friedkin',['1970s','kinetic','crime','rocket-fuel'],'pursuit reduced to pure urban momentum','🚇',3,4),
  F('A Clockwork Orange',1971,'Stanley Kubrick',['1970s','stylish','macabre','philosophical'],'violence choreographed as pop nightmare','🥛',4,4),
  F('The Devils',1971,'Ken Russell',['1970s','unwatchable','macabre','esoteric'],'religion and power combust into hysteria','⛪',5,4),
  F('The Last Picture Show',1971,'Peter Bogdanovich',['1970s','nostalgic','tender','beautiful-damage'],'small-town youth watches a world fade','🎞',3,5),
  F('Aguirre, the Wrath of God',1972,'Werner Herzog',['1970s','esoteric','unwatchable','liminal'],'mad ambition drifts into jungle myth','🛶',5,4),
  F('The Discreet Charm of the Bourgeoisie',1972,'Luis Buñuel',['1970s','dream','playful','esoteric'],'dinner plans repeatedly fail reality','🍽',5,4),
  F('The Long Goodbye',1973,'Robert Altman',['1970s','night-city','crime','playful'],'a detective wakes up in the wrong decade','🐈',4,5),
  F('The Holy Mountain',1973,'Alejandro Jodorowsky',['1970s','esoteric','dream','underground'],'spiritual spectacle eating its own symbols','🜏',5,3),
  F('Badlands',1973,'Terrence Malick',['1970s','beautiful-damage','crime','romantic'],'murder floats through postcard America','🌾',4,4),
  F('The Conversation',1974,'Francis Ford Coppola',['1970s','paranoid','philosophical','night-city'],'surveillance turns inward','🎧',5,4),
  F('A Woman Under the Influence',1974,'John Cassavetes',['1970s','emotional','unwatchable','beautiful-damage'],'love cannot fix a collapsing household','🥀',4,5),
  F('Dog Day Afternoon',1975,'Sidney Lumet',['1970s','kinetic','crime','emotional'],'a bank robbery becomes public theater','📣',4,5),
  F('Nashville',1975,'Robert Altman',['1970s','social','playful','dark'],'America sings while coming apart','🎤',4,4),
  F('Picnic at Hanging Rock',1975,'Peter Weir',['1970s','liminal','dream','macabre'],'schoolgirls vanish into geological time','🪨',5,5),
  F('Network',1976,'Sidney Lumet',['1970s','angry','media','kinetic'],'television monetizes a nervous breakdown','📺',4,5),
  F('Taxi Driver',1976,'Martin Scorsese',['1970s','night-city','dark','beautiful-damage'],'loneliness curdles under neon','🚕',4,5),
  F('Sorcerer',1977,'William Friedkin',['1970s','rocket-fuel','kinetic','unwatchable'],'four desperate men drive explosives through hell','🚚',5,4),
  F('Eraserhead',1977,'David Lynch',['1970s','liminal','dream','underground'],'industrial parenthood nightmare','🍼',5,4),
  F('Suspiria',1977,'Dario Argento',['1970s','horror','dream','stylish'],'primary-color witchcraft attacks architecture','🩰',5,5),
  F('Stalker',1979,'Andrei Tarkovsky',['1970s','liminal','philosophical','25th-hour'],'three men enter a zone of desire','🚪',5,4),
  F('All That Jazz',1979,'Bob Fosse',['1970s','rocket-fuel','beautiful-damage','stylish'],'show business dances with mortality','🎩',4,5),

  // 1980s
  F('Possession',1981,'Andrzej Żuławski',['1980s','psychosexual','macabre','unwatchable'],'a breakup mutates into cosmic body horror','🫀',5,5),
  F('Thief',1981,'Michael Mann',['1980s','night-city','crime','stylish'],'professional obsession under electric blue','💎',4,5),
  F('Blow Out',1981,'Brian De Palma',['1980s','curious','crime','night-city'],'sound recording finds a conspiracy','🎙',4,5),
  F('The King of Comedy',1982,'Martin Scorsese',['1980s','dark','playful','beautiful-damage'],'celebrity hunger smiles too long','🎤',4,5),
  F('Videodrome',1983,'David Cronenberg',['1980s','cyber','brainfuck','psychosexual'],'media grows new flesh','📺',5,4),
  F('Liquid Sky',1982,'Slava Tsukerman',['1980s','underground','night-city','psychosexual','campy'],'new-wave aliens feed on orgasm','💄',5,3),
  F('The Hunger',1983,'Tony Scott',['1980s','psychosexual','night-city','stylish'],'vampire chic in blue smoke','🩸',4,5),
  F('Paris, Texas',1984,'Wim Wenders',['1980s','tender','liminal','beautiful-damage'],'a lost man walks back toward intimacy','🌵',5,5),
  F('Repo Man',1984,'Alex Cox',['1980s','counterculture','playful','esoteric'],'punk Los Angeles chases a glowing Chevy','🚗',5,4),
  F('After Hours',1985,'Martin Scorsese',['1980s','night-city','elegant-panic','playful'],'downtown keeps inventing new disasters','🌃',4,5),
  F('Brazil',1985,'Terry Gilliam',['1980s','brainfuck','dark','playful'],'bureaucracy becomes industrial fantasy','🗂',5,4),
  F('Come and See',1985,'Elem Klimov',['1980s','unwatchable','dark','macabre'],'war strips childhood from a face','🔥',5,5),
  F('Mishima: A Life in Four Chapters',1985,'Paul Schrader',['1980s','stylish','philosophical','esoteric'],'a life arranged as aesthetic obsession','🌅',5,4),
  F('Blue Velvet',1986,'David Lynch',['1980s','psychosexual','night-city','macabre'],'suburbia opens a hidden red room','👂',5,5),
  F('Mona Lisa',1986,'Neil Jordan',['1980s','night-city','crime','romantic'],'a driver falls into Soho sadness','🚕',4,4),
  F('Wings of Desire',1987,'Wim Wenders',['1980s','romantic','philosophical','liminal'],'an angel longs for human weight','🪽',5,5),
  F('Near Dark',1987,'Kathryn Bigelow',['1980s','horror','romantic','night-city'],'vampires ride the highways at dawn','🩸',4,5),
  F('Akira',1988,'Katsuhiro Otomo',['1980s','cyber','kinetic','night-city'],'youth rage detonates neo-Tokyo','🏍',5,5),
  F('They Live',1988,'John Carpenter',['1980s','counterculture','campy','angry'],'sunglasses reveal the ruling class','🕶',5,4),
  F('Tetsuo: The Iron Man',1989,'Shinya Tsukamoto',['1980s','cyber','underground','rocket-fuel'],'flesh accelerates into scrap metal','⚙',5,3),
  F('Do the Right Thing',1989,'Spike Lee',['1980s','kinetic','angry','city'],'summer heat pushes a block toward rupture','🔥',4,5),

  // 1990s / early Y2K expansion
  F('Pump Up the Volume',1990,'Allan Moyle',['1990s','counterculture','night-city','tender'],'pirate radio turns loneliness outward','📻',4,4),
  F('Slacker',1990,'Richard Linklater',['1990s','counterculture','playful','philosophical'],'Austin drifts from monologue to monologue','☕',5,3),
  F('Trust',1990,'Hal Hartley',['1990s','tender-weirdos','romantic','underground'],'deadpan outsiders make a strange pact','🧃',5,4),
  F('Delicatessen',1991,'Jean-Pierre Jeunet, Marc Caro',['1990s','playful','macabre','stylish'],'post-apocalypse as cannibal clockwork','🥩',4,5),
  F('Until the End of the World',1991,'Wim Wenders',['1990s','cyber','dream','philosophical'],'the world ends inside recorded dreams','🌍',5,3),
  F('Night on Earth',1991,'Jim Jarmusch',['1990s','night-city','tender','playful'],'five taxi rides through one long night','🚕',4,4),
  F('Barton Fink',1991,'Joel Coen',['1990s','brainfuck','dark','liminal'],'Hollywood writer enters wallpaper hell','🛎',5,4),
  F('My Own Private Idaho',1991,'Gus Van Sant',['1990s','tender','counterculture','dream'],'street kids drift through Shakespearean longing','🛣',5,5),
  F('Basic Instinct',1992,'Paul Verhoeven',['1990s','psychosexual','night-city','stylish'],'desire turns interrogation into performance','🧊',3,4),
  F('Bad Lieutenant',1992,'Abel Ferrara',['1990s','unwatchable','night-city','beautiful-damage'],'corruption crawls toward grace','🏀',5,3),
  F('Orlando',1992,'Sally Potter',['1990s','playful','philosophical','stylish'],'identity crosses centuries without apology','🪞',4,5),
  F('Arizona Dream',1993,'Emir Kusturica',['1990s','dream','tender-weirdos','playful'],'American longing floats into absurdity','🐟',5,4),
  F('Dazed and Confused',1993,'Richard Linklater',['1990s','nostalgic','playful','counterculture'],'one night makes adolescence feel endless','🚗',4,5),
  F('Naked',1993,'Mike Leigh',['1990s','philosophical','night-city','dark'],'London becomes an apocalyptic monologue','🧥',5,4),
  F('Three Colors: Blue',1993,'Krzysztof Kieślowski',['1990s','tender','philosophical','beautiful-damage'],'grief tries to erase attachment','🔵',5,5),
  F('Chungking Express',1994,'Wong Kar-wai',['1990s','night-city','romantic','playful'],'lonely hearts collide at snack counters','🍍',5,5),
  F('Natural Born Killers',1994,'Oliver Stone',['1990s','kinetic','media','brainfuck'],'tabloid violence eats the screen','📺',4,4),
  F('Exotica',1994,'Atom Egoyan',['1990s','psychosexual','night-city','beautiful-damage'],'grief hides inside a strip club ritual','🌿',5,4),
  F('Heavenly Creatures',1994,'Peter Jackson',['1990s','dream','dark','tender'],'friendship invents a private universe','🦋',4,5),
  F('Safe',1995,'Todd Haynes',['1990s','liminal','philosophical','dark'],'modern life becomes an allergy','🧴',5,4),
  F('La Haine',1995,'Mathieu Kassovitz',['1990s','angry','kinetic','city'],'youth and pressure ricochet through Paris','⌚',5,5),
  F('Kids',1995,'Larry Clark',['1990s','underground','counterculture','dark'],'a summer day without adult guardrails','🛹',4,3),
  F('Dead Man',1995,'Jim Jarmusch',['1990s','liminal','macabre','esoteric'],'a western drifts toward the afterlife','🦴',5,4),
  F('Heat',1995,'Michael Mann',['1990s','night-city','crime','stylish'],'professional obsession meets under Los Angeles lights','🌃',4,5),
  F('Crash',1996,'David Cronenberg',['1990s','psychosexual','cyber','dark'],'desire learns the shape of twisted metal','🚘',5,4),
  F('Bound',1996,'Lana Wachowski, Lilly Wachowski',['1990s','psychosexual','crime','stylish'],'desire engineers a perfect double-cross','🖤',4,5),
  F('Trees Lounge',1996,'Steve Buscemi',['1990s','beautiful-damage','tender','night-city'],'barroom drift and failed adulthood','🍺',4,4),
  F('Breaking the Waves',1996,'Lars von Trier',['1990s','unwatchable','emotional','philosophical'],'faith turns love into self-destruction','🌊',5,4),
  F('Grosse Pointe Blank',1997,'George Armitage',['1990s','playful','crime','nostalgic'],'a hitman attends his high-school reunion','🎯',3,5),
  F('The Game',1997,'David Fincher',['1990s','brainfuck','elegant-panic','stylish'],'a rich man loses control of the frame','🎁',4,5),
  F('Boogie Nights',1997,'Paul Thomas Anderson',['1990s','kinetic','beautiful-damage','stylish'],'chosen family rides an industry boom and crash','🎥',4,5),
  F('Funny Games',1997,'Michael Haneke',['1990s','unwatchable','dark','brainfuck'],'violence turns the viewer into an accomplice','⛳',5,3),
  F('Taste of Cherry',1997,'Abbas Kiarostami',['1990s','philosophical','liminal','tender'],'a man searches for someone to bury him','🌄',5,4),
  F('Cube',1997,'Vincenzo Natali',['1990s','brainfuck','liminal','kinetic'],'strangers wake inside mathematical architecture','⬛',4,4),
  F('Buffalo ’66',1998,'Vincent Gallo',['1990s','tender-weirdos','romantic','beautiful-damage'],'hostage romance limps toward vulnerability','🎳',5,4),
  F('Pi',1998,'Darren Aronofsky',['1990s','philosophical','brainfuck','rocket-fuel'],'pattern hunger overheats a mathematician','π',5,3),
  F('Velvet Goldmine',1998,'Todd Haynes',['1990s','stylish','psychosexual','nostalgic'],'glam mythology rebuilt through memory','✨',4,5),
  F('Rushmore',1998,'Wes Anderson',['1990s','playful','tender-weirdos','nostalgic'],'a teenage overachiever weaponizes charm','🏫',3,5),
  F('Eyes Wide Shut',1999,'Stanley Kubrick',['1990s','psychosexual','night-city','dream'],'marriage wanders into masked desire','🎭',5,5),
  F('Magnolia',1999,'Paul Thomas Anderson',['1990s','emotional','beautiful-damage','kinetic'],'private pain converges under impossible weather','🐸',4,5),
  F('Fight Club',1999,'David Fincher',['1990s','counterculture','kinetic','brainfuck'],'consumer malaise punches itself awake','🥊',4,5),
  F('The Limey',1999,'Steven Soderbergh',['1990s','crime','stylish','experimental'],'revenge edited through memory','🌴',4,4),
  F('Ghost Dog: The Way of the Samurai',1999,'Jim Jarmusch',['1990s','night-city','crime','esoteric'],'a hitman lives by an ancient code','🐦',5,4),
  F('Election',1999,'Alexander Payne',['1990s','playful','dark','nostalgic'],'ambition weaponizes a student election','🗳',3,5),
  F('Sexy Beast',2000,'Jonathan Glazer',['2000s','crime','elegant-panic','stylish'],'retirement is interrupted by pure menace','☀',4,5),
  F('Memento',2000,'Christopher Nolan',['2000s','brainfuck','crime','kinetic'],'memory failure becomes narrative structure','📸',4,5),
  F('Battle Royale',2000,'Kinji Fukasaku',['2000s','kinetic','dark','rocket-fuel'],'teen survival becomes state policy','🎒',4,5),
  F('Amélie',2001,'Jean-Pierre Jeunet',['2000s','playful','romantic','tender'],'private whimsy nudges strangers together','🍓',3,5),
  F('Mulholland Drive',2001,'David Lynch',['2000s','dream','brainfuck','night-city'],'Hollywood identity melts after midnight','🔑',5,5),
  F('Donnie Darko',2001,'Richard Kelly',['2000s','brainfuck','nostalgic','end-times'],'teen alienation meets apocalyptic time logic','🐇',5,4),
  F('Y Tu Mamá También',2001,'Alfonso Cuarón',['2000s','romantic','kinetic','beautiful-damage'],'a road trip outruns adolescence','🚙',4,5),
  F('Punch-Drunk Love',2002,'Paul Thomas Anderson',['2000s','romantic','tender-weirdos','kinetic'],'rage and loneliness find a strange love story','💙',4,5),
  F('28 Days Later',2002,'Danny Boyle',['2000s','kinetic','horror','end-times'],'empty London wakes up infected','🧟',4,5),
  F('Oldboy',2003,'Park Chan-wook',['2000s','brainfuck','kinetic','macabre'],'revenge discovers an unbearable answer','🐙',5,5),
  F('The Dreamers',2003,'Bernardo Bertolucci',['2000s','psychosexual','romantic','cinephile'],'young cinephiles barricade themselves in desire','🎞',4,4),
  F('Eternal Sunshine of the Spotless Mind',2004,'Michel Gondry',['2000s','romantic','brainfuck','tender'],'memory erasure reveals what love leaves behind','🧠',5,5),
  F('Primer',2004,'Shane Carruth',['2000s','brainfuck','philosophical','underground'],'garage engineers accidentally invent time','🔧',5,3),
  F('The Life Aquatic with Steve Zissou',2004,'Wes Anderson',['2000s','playful','tender-weirdos','nostalgic'],'grief hides inside handmade adventure','🐆',4,5),
  F('Kiss Kiss Bang Bang',2005,'Shane Black',['2000s','playful','crime','kinetic'],'noir gets drunk on self-awareness','🔫',3,5),
  F('Brick',2005,'Rian Johnson',['2000s','crime','stylish','nostalgic'],'high school speaks hard-boiled detective','🧱',4,4),
  F('The Prestige',2006,'Christopher Nolan',['2000s','brainfuck','dark','stylish'],'rival magicians turn obsession into machinery','🎩',4,5),
  F('Children of Men',2006,'Alfonso Cuarón',['2000s','end-times','kinetic','philosophical'],'hope moves through a collapsing world','👶',5,5),
  F('In Bruges',2008,'Martin McDonagh',['2000s','playful','dark','tender'],'guilt waits in a medieval postcard','🦢',4,5),
  F('Synecdoche, New York',2008,'Charlie Kaufman',['2000s','philosophical','brainfuck','beautiful-damage'],'a life becomes an impossible theater model','🏙',5,4),
  F('Enter the Void',2009,'Gaspar Noé',['2000s','25th-hour','dream','unwatchable'],'consciousness floats above neon Tokyo','🌈',5,4),

  // 2010s–2020s broadening / directors Julie is likely to have more of
  F('Black Swan',2010,'Darren Aronofsky',['2010s','psychosexual','brainfuck','macabre'],'perfection fractures into body horror','🩰',4,5),
  F('Drive',2011,'Nicolas Winding Refn',['2010s','night-city','stylish','crime'],'romance and violence glow in synth neon','🦂',4,5),
  F('Melancholia',2011,'Lars von Trier',['2010s','depressed','philosophical','end-times'],'depression meets a literal planet','🪐',5,4),
  F('Holy Motors',2012,'Leos Carax',['2010s','brainfuck','esoteric','playful'],'a man spends a day becoming other people','🚘',5,4),
  F('The Hunt',2012,'Thomas Vinterberg',['2010s','emotional','dark','unwatchable'],'a community closes around an accusation','🦌',3,5),
  F('Frances Ha',2012,'Noah Baumbach',['2010s','tender','playful','nostalgic'],'friendship and drift in black-and-white New York','🩰',3,5),
  F('Enemy',2013,'Denis Villeneuve',['2010s','brainfuck','dream','psychosexual'],'a man finds his double and loses certainty','🕷',5,4),
  F('Under the Skin',2013,'Jonathan Glazer',['2010s','liminal','esoteric','25th-hour'],'an alien studies human bodies from the roadside','🖤',5,4),
  F('The Grand Budapest Hotel',2014,'Wes Anderson',['2010s','playful','nostalgic','stylish'],'elegance remembers a vanished world','🔑',3,5),
  F('Gone Girl',2014,'David Fincher',['2010s','psychosexual','dark','stylish'],'marriage becomes a media crime scene','📺',4,5),
  F('It Follows',2014,'David Robert Mitchell',['2010s','horror','liminal','night-city'],'dread walks at a steady human pace','🚶',4,5),
  F('The Lobster',2015,'Yorgos Lanthimos',['2010s','playful','dark','esoteric'],'romance becomes administrative coercion','🦞',4,5),
  F('The Handmaiden',2016,'Park Chan-wook',['2010s','psychosexual','romantic','stylish'],'desire rewrites a con from inside','🧤',5,5),
  F('Raw',2016,'Julia Ducournau',['2010s','psychosexual','horror','beautiful-damage'],'appetite turns adulthood carnivorous','🥩',4,5),
  F('Good Time',2017,'Benny Safdie, Josh Safdie',['2010s','rocket-fuel','night-city','crime'],'one bad night accelerates without mercy','💸',4,5),
  F('Phantom Thread',2017,'Paul Thomas Anderson',['2010s','psychosexual','romantic','stylish'],'love becomes a private system of control','🪡',4,5),
  F('You Were Never Really Here',2017,'Lynne Ramsay',['2010s','dark','beautiful-damage','night-city'],'violence arrives as broken memory','🔨',4,4),
  F('Climax',2018,'Gaspar Noé',['2010s','rocket-fuel','unwatchable','night-city'],'a dance party curdles into collective panic','🕺',5,4),
  F('Burning',2018,'Lee Chang-dong',['2010s','curious','dark','philosophical'],'desire and class simmer around a disappearance','🔥',5,5),
  F('The Favourite',2018,'Yorgos Lanthimos',['2010s','playful','psychosexual','dark'],'court politics becomes erotic knife-fighting','🦆',4,5),
  F('Parasite',2019,'Bong Joon Ho',['2010s','kinetic','dark','playful'],'class warfare hides inside architectural comedy','🏠',4,5),
  F('Uncut Gems',2019,'Benny Safdie, Josh Safdie',['2010s','rocket-fuel','elegant-panic','crime'],'bad decisions achieve gemstone velocity','💎',4,5),
  F('Portrait of a Lady on Fire',2019,'Céline Sciamma',['2010s','romantic','tender','harmonious'],'looking becomes a form of love','🔥',4,5),
  F('The Lighthouse',2019,'Robert Eggers',['2010s','macabre','liminal','brainfuck'],'two men rot together at the edge of the sea','🕯',5,4),
  F('Titane',2021,'Julia Ducournau',['2020s','psychosexual','macabre','tender-weirdos'],'metal, identity and tenderness fuse impossibly','🚗',5,5),
  F('The Worst Person in the World',2021,'Joachim Trier',['2020s','romantic','tender','playful'],'adulthood keeps changing shape mid-sentence','🌇',3,5),
  F('Everything Everywhere All at Once',2022,'Daniel Kwan, Daniel Scheinert',['2020s','brainfuck','kinetic','tender'],'multiverse chaos returns to kindness','🥯',4,5),
  F('Aftersun',2022,'Charlotte Wells',['2020s','tender','nostalgic','beautiful-damage'],'a daughter remembers what childhood missed','📹',4,5),
  F('Beau Is Afraid',2023,'Ari Aster',['2020s','brainfuck','unwatchable','macabre'],'anxiety expands into hostile cosmology','🚪',5,3),
  F('Poor Things',2023,'Yorgos Lanthimos',['2020s','playful','psychosexual','stylish'],'a woman discovers the world at full speed','🫧',4,5),
  F('The Zone of Interest',2023,'Jonathan Glazer',['2020s','unwatchable','dark','philosophical'],'domestic normality sits beside atrocity','🌳',5,4)
);


// Director depth: enough titles for a real five-film corridor instead of a one-card dead end.
FILMS.push(
  F('Memories of Murder',2003,'Bong Joon Ho',['2000s','crime','dark','curious'],'a murder investigation sinks into national unease','🌧',4,5),
  F('The Host',2006,'Bong Joon Ho',['2000s','kinetic','horror','playful'],'a monster movie with family and political teeth','🐟',4,5),
  F('Mother',2009,'Bong Joon Ho',['2000s','crime','dark','emotional'],'maternal devotion becomes detective obsession','🌿',4,5),
  F('Snowpiercer',2013,'Bong Joon Ho',['2010s','kinetic','dark','counterculture'],'class warfare runs the length of a train','🚆',4,5),
  F('Okja',2017,'Bong Joon Ho',['2010s','playful','dark','tender'],'corporate absurdity collides with animal love','🐖',3,5),
  F('Daddy Longlegs',2009,'Benny Safdie, Josh Safdie',['2000s','beautiful-damage','tender','kinetic'],'chaotic fatherhood on borrowed time','☎',4,5),
  F('Heaven Knows What',2014,'Benny Safdie, Josh Safdie',['2010s','beautiful-damage','night-city','dark'],'addiction and romance scrape against Manhattan','🧃',4,5),
  F('One Flew Over the Cuckoo’s Nest',1975,'Miloš Forman',['1970s','counterculture','emotional','dark'],'rebellion enters an institution and pays for it','🪟',4,5),
  F('Hair',1979,'Miloš Forman',['1970s','counterculture','playful','nostalgic'],'hippie exuberance dances toward war','🌼',3,5),
  F('The People vs. Larry Flynt',1996,'Miloš Forman',['1990s','counterculture','dark','playful'],'free speech becomes a carnival court case','📰',3,5),
  F('Following',1998,'Christopher Nolan',['1990s','crime','brainfuck','underground'],'a young voyeur follows the wrong stranger','🔑',4,4),
  F('Insomnia',2002,'Christopher Nolan',['2000s','crime','dark','liminal'],'guilt refuses to sleep under endless daylight','🌫',3,4),
  F('Inception',2010,'Christopher Nolan',['2010s','brainfuck','kinetic','dream'],'a heist descends through engineered dreams','🌀',4,5),
  F('Interstellar',2014,'Christopher Nolan',['2010s','philosophical','emotional','cosmic'],'love and survival stretch across spacetime','🪐',4,5),
  F('Shaun of the Dead',2004,'Edgar Wright',['2000s','playful','horror','kinetic'],'romantic stagnation meets zombie outbreak','🧟',3,5),
  F('Hot Fuzz',2007,'Edgar Wright',['2000s','playful','kinetic','crime'],'small-town policing turns operatic','🚓',3,5),
  F('Scott Pilgrim vs. the World',2010,'Edgar Wright',['2010s','playful','kinetic','nostalgic'],'romance becomes arcade combat','🎸',3,5),
  F('The World’s End',2013,'Edgar Wright',['2010s','playful','dark','nostalgic'],'a pub crawl confronts arrested adolescence','🍺',3,5),
  F('Sympathy for Mr. Vengeance',2002,'Park Chan-wook',['2000s','dark','crime','macabre'],'desperation starts a revenge chain','🟢',5,4),
  F('Lady Vengeance',2005,'Park Chan-wook',['2000s','stylish','crime','macabre'],'revenge is planned with ceremonial precision','🔴',5,5),
  F('Thirst',2009,'Park Chan-wook',['2000s','psychosexual','horror','macabre'],'faith and desire mutate through vampirism','🩸',5,5),
  F('Decision to Leave',2022,'Park Chan-wook',['2020s','romantic','crime','stylish'],'detective obsession becomes impossible intimacy','🌊',4,5),
  F('Dead Ringers',1988,'David Cronenberg',['1980s','psychosexual','dark','brainfuck'],'twin gynecologists merge into shared collapse','🔴',5,4),
  F('Naked Lunch',1991,'David Cronenberg',['1990s','brainfuck','esoteric','psychosexual'],'writing, drugs and insects share one hallucination','🪲',5,3),
  F('Spider',2002,'David Cronenberg',['2000s','brainfuck','dark','liminal'],'memory reconstructs a damaged childhood','🕸',5,3),
  F('A History of Violence',2005,'David Cronenberg',['2000s','dark','crime','philosophical'],'a peaceful identity cracks under old violence','🥛',4,5),
  F('El Topo',1970,'Alejandro Jodorowsky',['1970s','esoteric','underground','dream'],'a western walks into mystical initiation','🌵',5,3),
  F('Fando y Lis',1968,'Alejandro Jodorowsky',['1960s','underground','esoteric','unwatchable'],'lovers cross a wasteland toward a mythical city','🪨',5,2),
  F('Julien Donkey-Boy',1999,'Harmony Korine',['1990s','underground','unwatchable','beautiful-damage'],'family life flickers through corrupted video','📼',5,2),
  F('Trash Humpers',2009,'Harmony Korine',['2000s','underground','unwatchable','c-films'],'VHS goblins vandalize the night','🗑',5,1),
  F('I Stand Alone',1998,'Gaspar Noé',['1990s','unwatchable','dark','night-city'],'hatred narrates itself toward catastrophe','🔨',5,2),
  F('Irreversible',2002,'Gaspar Noé',['2000s','unwatchable','kinetic','macabre'],'time runs backward through unbearable violence','🚇',5,2),
  F('Vortex',2021,'Gaspar Noé',['2020s','unwatchable','tender','beautiful-damage'],'old age splits a shared apartment in two','🫀',4,3),
  F('Days of Being Wild',1990,'Wong Kar-wai',['1990s','romantic','night-city','nostalgic'],'restlessness circles desire in humid rooms','🕰',5,5),
  F('Happy Together',1997,'Wong Kar-wai',['1990s','romantic','beautiful-damage','night-city'],'a relationship keeps breaking in Buenos Aires','🌊',5,5),
  F('In the Mood for Love',2000,'Wong Kar-wai',['2000s','romantic','night-city','stylish'],'desire survives by remaining unconsummated','🍜',5,5),
  F('2046',2004,'Wong Kar-wai',['2000s','romantic','dream','night-city'],'memory invents a future it cannot escape','🚂',5,5),
  F('Totally F***ed Up',1993,'Gregg Araki',['1990s','underground','counterculture','tender'],'queer friends document the end of their world','📹',5,4),
  F('Kaboom',2010,'Gregg Araki',['2010s','psychosexual','brainfuck','playful'],'college desire stumbles into apocalypse','💥',5,4),
  F('Ivan’s Childhood',1962,'Andrei Tarkovsky',['1960s','dream','dark','liminal'],'war reaches childhood through haunted images','🌲',5,4),
  F('Mirror',1975,'Andrei Tarkovsky',['1970s','dream','liminal','philosophical'],'memory moves by weather instead of chronology','🪞',5,4),
  F('Nostalghia',1983,'Andrei Tarkovsky',['1980s','liminal','philosophical','25th-hour'],'homesickness turns landscape into ritual','🕯',5,3),
  F('The Sacrifice',1986,'Andrei Tarkovsky',['1980s','philosophical','liminal','end-times'],'a man bargains with existence at the brink','🌳',5,3),
  F('Before Sunset',2004,'Richard Linklater',['2000s','romantic','tender','philosophical'],'nine years collapse into one Paris walk','🌇',4,5),
  F('Before Midnight',2013,'Richard Linklater',['2010s','romantic','tender','beautiful-damage'],'love survives long enough to become argument','🌒',4,5),
  F('Waking Life',2001,'Richard Linklater',['2000s','philosophical','dream','esoteric'],'a lucid dream becomes a philosophy seminar','🌀',5,4),
  F('A Scanner Darkly',2006,'Richard Linklater',['2000s','cyber','brainfuck','dark'],'surveillance and addiction dissolve identity','🕶',5,4)
);

FILMS.push(
  F('Trainspotting',1996,'Danny Boyle',['1990s','kinetic','counterculture'],'filthy velocity and black comedy','🚽',5,4),
  F('Shallow Grave',1994,'Danny Boyle',['1990s','crime','dark','kinetic'],'flatmates discover money and paranoia','💼',4,4),
  F('Sunshine',2007,'Danny Boyle',['2000s','cosmic','kinetic','philosophical'],'a dying sun turns mission into obsession','☀',4,4),
  F('Tokyo Fist',1995,'Shinya Tsukamoto',['1990s','rocket-fuel','underground','body'],'boxing turns the city into bruised flesh','🥊',5,3),
  F('Vital',2004,'Shinya Tsukamoto',['2000s','dream','macabre','philosophical'],'anatomy class becomes memory ritual','🫀',5,3),
  F('Rushmore',1998,'Wes Anderson',['1990s','playful','tender-weirdos'],'precocious ambition in school uniform','🏫',3,5),
  F('The Royal Tenenbaums',2001,'Wes Anderson',['2000s','tender-weirdos','nostalgic','playful'],'a damaged family poses beautifully','🎾',3,5),
  F('Fantastic Mr. Fox',2009,'Wes Anderson',['2000s','playful','tender','nostalgic'],'midlife crisis in stop-motion corduroy','🦊',3,5),
  F('Se7en',1995,'David Fincher',['1990s','macabre','crime','dark'],'a city becomes a moral crime scene','📦',4,5),
  F('Zodiac',2007,'David Fincher',['2000s','curious','crime','dark'],'obsession outlives the investigation','📰',4,5),
  F('The Social Network',2010,'David Fincher',['2010s','kinetic','dark','stylish'],'ambition codes friendship into litigation','💻',3,5),
  F('Goodfellas',1990,'Martin Scorsese',['1990s','kinetic','crime','stylish'],'gangster life seduces at full speed','🍝',3,5),
  F('Bringing Out the Dead',1999,'Martin Scorsese',['1990s','night-city','beautiful-damage','25th-hour'],'an exhausted paramedic haunts Manhattan nights','🚑',5,4),
  F('The Color of Money',1986,'Martin Scorsese',['1980s','kinetic','stylish','nostalgic'],'pool-hall mentorship runs on ego','🎱',3,4),
  F('Mister Lonely',2007,'Harmony Korine',['2000s','tender-weirdos','dream','underground'],'celebrity impersonators build a fragile commune','🌈',5,3),
  F('Spring Breakers',2012,'Harmony Korine',['2010s','night-city','psychosexual','beautiful-damage'],'party fantasy repeats until it becomes menace','🔫',4,4),
  F('The Dance of Reality',2013,'Alejandro Jodorowsky',['2010s','dream','esoteric','playful'],'autobiography remade as mystical carnival','🌈',5,3),
  F('Endless Poetry',2016,'Alejandro Jodorowsky',['2010s','dream','esoteric','tender'],'artistic awakening staged as memory pageant','🎨',5,3),
  F('Man on the Moon',1999,'Miloš Forman',['1990s','playful','beautiful-damage'],'performance art hides inside a biopic','🌙',3,5)
);

FILMS.push(
  F('Spirited Away',2001,'Hayao Miyazaki',['2000s','dream','playful','tender','esoteric'],'a child crosses into a bathhouse spirit world','🐉',4,5)
);

FILMS.push(
  F('The Pleasure of Being Robbed',2008,'Josh Safdie',['2000s','underground','playful','night-city'],'a petty thief drifts through downtown New York','👜',4,4)
);

// Keep the richer original seed when an expansion title duplicates it.
{
  const seen = new Set();
  for (let i = 0; i < FILMS.length; ) {
    const k = `${FILMS[i].title.toLowerCase()}|${FILMS[i].year}`;
    if (seen.has(k)) FILMS.splice(i, 1);
    else { seen.add(k); i++; }
  }
}

// Normalize decade shorthand used by the original hand-built vibe taxonomy.
for (const film of FILMS) {
  const d = Math.floor(film.year / 10) * 10;
  const short = ({1920:'20s',1930:'30s',1940:'40s',1950:'50s',1960:'60s',1970:'70s',1980:'80s',1990:'90s',2000:'2000s',2010:'2010s',2020:'2020s'})[d];
  if (short && !film.tags.includes(short)) film.tags.push(short);
}
