/* v0.4 curated expansion — long-tail films chosen to deepen the existing semantic rooms. */
const V04_CURATED = [
  // Japanese cyber/body/night-city
  F("Tetsuo II: Body Hammer",1992,"Shinya Tsukamoto",['90s','cyber','kinetic','weird','underground','body-horror'],'industrial body thunder','⚙',5,3),
  F("Tokyo Fist",1995,"Shinya Tsukamoto",['90s','kinetic','body-horror','dark','psychosexual'],'flesh and jealousy in overdrive','🥊',5,4),
  F("Bullet Ballet",1998,"Shinya Tsukamoto",['90s','night-city','dark','kinetic','beautiful-damage'],'gunmetal grief at midnight','🔫',5,3),
  F("Vital",2004,"Shinya Tsukamoto",['2000s','body-horror','dream','tender','dark'],'anatomy-class mourning trance','🫀',5,4),
  F("Rubber's Lover",1996,"Shozin Fukui",['90s','cyber','underground','experimental','unwatchable'],'industrial psychic abrasion','📡',5,2),
  F("964 Pinocchio",1991,"Shozin Fukui",['90s','cyber','underground','weird','body-horror'],'street-level cybernetic breakdown','🦾',5,2),
  F("Electric Dragon 80.000 V",2001,"Sogo Ishii",['2000s','kinetic','cyber','rocket-fuel','weird'],'feedback-guitar superhero voltage','⚡',5,4),
  F("Crazy Thunder Road",1980,"Sogo Ishii",['counterculture','kinetic','underground','angry','rocket-fuel'],'biker-punk acceleration','🏍',5,3),
  F("Burst City",1982,"Sogo Ishii",['counterculture','kinetic','underground','angry','rocket-fuel'],'punk wasteland detonation','💥',5,3),
  F("Angel Dust",1994,"Gakuryu Ishii",['90s','night-city','dark','brainfuck','psychological'],'subway serial-killer dissociation','🚇',5,4),
  F("August in the Water",1995,"Gakuryu Ishii",['90s','dream','liminal','cosmic','tender'],'adolescent cosmic humidity','💧',5,4),
  F("Labyrinth of Dreams",1997,"Gakuryu Ishii",['90s','dream','romantic','dark','liminal'],'fatal romance in monochrome','🚌',5,4),
  F("Cure",1997,"Kiyoshi Kurosawa",['90s','horror','liminal','dark','brainfuck'],'hypnotic procedural emptiness','🌀',5,5),
  F("Charisma",1999,"Kiyoshi Kurosawa",['90s','philosophical','weird','liminal','dark'],'ecological moral fever dream','🌳',5,4),
  F("Bright Future",2002,"Kiyoshi Kurosawa",['2000s','tender','weird','night-city','beautiful-damage'],'jellyfish youth alienation','🪼',5,4),
  F("Pulse",2001,"Kiyoshi Kurosawa",['2000s','horror','liminal','y2k','lonely','end-times'],'internet loneliness apocalypse','🖥',5,5),
  F("Suicide Club",2001,"Sion Sono",['2000s','horror','weird','y2k','dark','end-times'],'pop-culture mass-hysteria nightmare','🚉',5,4),
  F("Noriko's Dinner Table",2005,"Sion Sono",['2000s','dark','identity','weird','beautiful-damage'],'identity fracture family epic','🍽',5,4),
  F("Love Exposure",2008,"Sion Sono",['2000s','kinetic','romantic','weird','psychosexual','rocket-fuel'],'four-hour holy pervert sprint','📸',5,5),
  F("Cold Fish",2010,"Sion Sono",['2010s','crime','dark','macabre','psychosexual'],'fish-shop homicidal pressure cooker','🐟',4,4),
  F("Guilty of Romance",2011,"Sion Sono",['2010s','psychosexual','dark','night-city','beautiful-damage'],'neon erotic self-destruction','🌹',4,5),
  F("Visitor Q",2001,"Takashi Miike",['2000s','underground','dark','weird','macabre','unwatchable'],'family taboo grenade','📹',5,3),
  F("Gozu",2003,"Takashi Miike",['2000s','weird','dream','crime','body-horror'],'yakuza Lynchian mutation','🐄',5,4),
  F("Dead or Alive",1999,"Takashi Miike",['90s','crime','kinetic','weird','rocket-fuel'],'yakuza apocalypse speedrun','💣',5,4),
  F("Ichi the Killer",2001,"Takashi Miike",['2000s','crime','unwatchable','psychosexual','macabre'],'ultraviolent manga psychosis','🔪',5,4),
  F("Blue Spring",2001,"Toshiaki Toyoda",['2000s','counterculture','dark','tender','beautiful-damage'],'rooftop delinquent melancholy','🏫',5,4),
  F("9 Souls",2003,"Toshiaki Toyoda",['2000s','crime','tender-weirdos','beautiful-damage','road'],'escaped-prisoner bruised tenderness','🚐',5,4),
  F("All About Lily Chou-Chou",2001,"Shunji Iwai",['2000s','y2k','tender','dark','beautiful-damage','cyber'],'internet-age adolescent ache','🎧',5,5),
  F("Kamikaze Girls",2004,"Tetsuya Nakashima",['2000s','playful','campy','tender-weirdos','stylish'],'Lolita biker friendship confection','🧁',4,5),
  F("Survive Style 5+",2004,"Gen Sekiguchi",['2000s','weird','playful','kinetic','stylish'],'commercial-pop surreal pinball','🦜',5,5),
  F("The Taste of Tea",2004,"Katsuhito Ishii",['2000s','tender-weirdos','playful','dream','harmonious'],'family surrealism in summer air','🍵',5,5),
  F("Funky Forest: The First Contact",2005,"Katsuhito Ishii",['2000s','weird','underground','playful','dream'],'sketch-comedy alien subconscious','🛸',5,4),

  // Taiwan / Hong Kong / Southeast Asian drift
  F("Rebels of the Neon God",1992,"Tsai Ming-liang",['90s','night-city','lonely','tender','liminal'],'Taipei youth neon drift','🛵',5,4),
  F("Vive L'Amour",1994,"Tsai Ming-liang",['90s','lonely','liminal','tender','night-city'],'empty-apartment urban ache','🏢',5,4),
  F("The River",1997,"Tsai Ming-liang",['90s','dark','tender','liminal','psychosexual'],'family illness and wet concrete','🌧',5,4),
  F("The Hole",1998,"Tsai Ming-liang",['90s','end-times','liminal','lonely','musical'],'apocalyptic apartment musical','🕳',5,4),
  F("What Time Is It There?",2001,"Tsai Ming-liang",['2000s','lonely','tender','liminal','romantic'],'time-zone grief and distance','⌚',5,5),
  F("Goodbye, Dragon Inn",2003,"Tsai Ming-liang",['2000s','liminal','lonely','cinema','tender'],'ghosts in a dying movie palace','🎞',5,5),
  F("Millennium Mambo",2001,"Hou Hsiao-hsien",['2000s','y2k','night-city','tender','beautiful-damage'],'blue-neon memory drift','💙',5,5),
  F("Made in Hong Kong",1997,"Fruit Chan",['90s','night-city','counterculture','tender','beautiful-damage'],'housing-estate youth tragedy','🏙',5,5),
  F("Tropical Malady",2004,"Apichatpong Weerasethakul",['2000s','dream','romantic','liminal','cosmic'],'jungle desire turns mythic','🐅',5,5),
  F("Syndromes and a Century",2006,"Apichatpong Weerasethakul",['2000s','dream','harmonious','liminal','tender'],'memory reincarnated as architecture','🏥',5,4),
  F("Uncle Boonmee Who Can Recall His Past Lives",2010,"Apichatpong Weerasethakul",['2010s','dream','cosmic','tender','liminal'],'gentle ghosts at dinner','🐒',5,5),
  F("Cemetery of Splendour",2015,"Apichatpong Weerasethakul",['2010s','dream','sleepy','liminal','cosmic'],'sleeping soldiers and buried kings','🛏',5,4),

  // Eastern/Central European strange cinema
  F("The Hourglass Sanatorium",1973,"Wojciech Jerzy Has",['70s','dream','esoteric','surreal','liminal'],'decaying baroque memory maze','⏳',5,4),
  F("The Saragossa Manuscript",1965,"Wojciech Jerzy Has",['60s','esoteric','dream','playful','philosophical'],'nested occult story labyrinth','📖',5,4),
  F("On the Silver Globe",1988,"Andrzej Żuławski",['80s','cosmic','unwatchable','experimental','philosophical'],'unfinished lunar civilization fever','🌕',5,4),
  F("The Devil",1972,"Andrzej Żuławski",['70s','dark','macabre','kinetic','psychological'],'historical possession frenzy','😈',5,4),
  F("The Third Part of the Night",1971,"Andrzej Żuławski",['70s','dark','dream','kinetic','beautiful-damage'],'wartime hallucination under pressure','🪳',5,4),
  F("Valerie and Her Week of Wonders",1970,"Jaromil Jireš",['70s','dream','esoteric','psychosexual','gothic'],'adolescent gothic fairy logic','🩸',5,5),
  F("The Cremator",1969,"Juraj Herz",['60s','macabre','dark','weird','political'],'crematorium bourgeois nightmare','⚱',5,5),
  F("Morgiana",1972,"Juraj Herz",['70s','gothic','psychosexual','dream','macabre'],'poisoned sister gothic delirium','🦚',5,5),
  F("The Ear",1970,"Karel Kachyňa",['70s','paranoid','political','night-city','dark'],'surveillance marriage chamber piece','👂',5,4),
  F("Marketa Lazarová",1967,"František Vláčil",['60s','historical','dark','poetic','unwatchable'],'medieval mud-and-ecstasy epic','🦌',5,4),
  F("The Fifth Seal",1976,"Zoltán Fábri",['70s','philosophical','dark','political','moral'],'ethics under fascist pressure','🕯',5,5),
  F("Taxidermia",2006,"György Pálfi",['2000s','body-horror','macabre','weird','unwatchable'],'three generations of bodily grotesque','🧵',5,4),
  F("Hukkle",2002,"György Pálfi",['2000s','experimental','weird','rural','macabre'],'village sound-design murder puzzle','🐸',5,4),
  F("Kontroll",2003,"Nimród Antal",['2000s','night-city','liminal','kinetic','dark'],'Budapest subway purgatory','🚇',5,5),
  F("Werckmeister Harmonies",2000,"Béla Tarr",['2000s','liminal','philosophical','dark','unwatchable'],'whale-circus cosmic dread','🐋',5,5),
  F("The Turin Horse",2011,"Béla Tarr",['2010s','unwatchable','end-times','philosophical','dark'],'the world quietly stops','🐎',5,4),
  F("Damnation",1988,"Béla Tarr",['80s','night-city','dark','lonely','beautiful-damage'],'rain-soaked barroom damnation','🌧',5,4),
  F("The Color of Pomegranates",1969,"Sergei Parajanov",['60s','esoteric','experimental','poetic','dream'],'iconographic poetry tableau','🍎',5,5),
  F("Shadows of Forgotten Ancestors",1965,"Sergei Parajanov",['60s','romantic','folk','kinetic','esoteric'],'Carpathian love in ritual color','🪵',5,5),
  F("Kin-dza-dza!",1986,"Georgiy Daneliya",['80s','cosmic','weird','satire','tender-weirdos'],'Soviet desert sci-fi absurdism','🏜',5,4),
  F("Dead Man's Letters",1986,"Konstantin Lopushansky",['80s','end-times','dark','philosophical','liminal'],'nuclear aftermath monastery gloom','☢',5,4),
  F("Visitor to a Museum",1989,"Konstantin Lopushansky",['80s','end-times','esoteric','dark','liminal'],'post-apocalyptic pilgrimage','🏚',5,3),
  F("Khrustalyov, My Car!",1998,"Aleksei German",['90s','unwatchable','dark','historical','kinetic'],'Stalinist delirium avalanche','🚗',5,3),
  F("Hard to Be a God",2013,"Aleksei German",['2010s','unwatchable','dark','philosophical','macabre'],'three hours of medieval sewage','🪣',5,3),
  F("Assa",1987,"Sergei Solovyov",['80s','counterculture','romantic','weird','music'],'Soviet rock youth collision','🎸',5,4),
  F("The Needle",1988,"Rashid Nugmanov",['80s','counterculture','night-city','dark','music'],'Soviet post-punk narcotic noir','💉',5,4),

  // French/Belgian/Hungarian fever
  F("Boy Meets Girl",1984,"Leos Carax",['80s','romantic','night-city','lonely','stylish'],'black-and-white young-love ache','☎',5,4),
  F("Mauvais Sang",1986,"Leos Carax",['80s','romantic','kinetic','night-city','stylish'],'disease-heist neon yearning','🩸',5,5),
  F("The Lovers on the Bridge",1991,"Leos Carax",['90s','romantic','night-city','beautiful-damage','kinetic'],'homeless love as fireworks','🌉',5,5),
  F("Holy Motors",2012,"Leos Carax",['2010s','weird','dream','philosophical','night-city'],'cinema changes bodies all night','🚘',5,5),
  F("Baxter",1989,"Jérôme Boivin",['80s','dark','weird','macabre','satire'],'misanthropic bull terrier philosophy','🐕',5,4),
  F("Man Bites Dog",1992,"Rémy Belvaux, André Bonzel, Benoît Poelvoorde",['90s','crime','dark','macabre','mockumentary'],'serial-killer documentary complicity','🎥',5,4),
  F("Calvaire",2004,"Fabrice Du Welz",['2000s','horror','weird','macabre','psychosexual'],'rural Belgian nightmare hospitality','🎄',5,4),
  F("Ex Drummer",2007,"Koen Mortier",['2000s','counterculture','dark','macabre','underground'],'Belgian punk cruelty circus','🥁',5,3),
  F("Demonlover",2002,"Olivier Assayas",['2000s','y2k','cyber','psychosexual','night-city'],'corporate hentai techno paranoia','💻',5,5),
  F("Irma Vep",1996,"Olivier Assayas",['90s','cinema','playful','night-city','stylish'],'film-set identity flirtation','🖤',5,5),

  // Psychosexual / damaged intimacy
  F("The Piano Teacher",2001,"Michael Haneke",['2000s','psychosexual','dark','unwatchable','beautiful-damage'],'repression sharpened into a blade','🎹',5,5),
  F("Bitter Moon",1992,"Roman Polanski",['90s','psychosexual','dark','romantic','campy'],'cruise-ship erotic warfare','🚢',4,4),
  F("In the Realm of the Senses",1976,"Nagisa Oshima",['70s','psychosexual','unwatchable','romantic','dark'],'desire pursued past reason','🫦',5,4),
  F("The Duke of Burgundy",2014,"Peter Strickland",['2010s','psychosexual','romantic','dream','stylish'],'ritual kink and tenderness','🦋',5,5),
  F("Secretary",2002,"Steven Shainberg",['2000s','psychosexual','romantic','tender-weirdos','playful'],'BDSM office love story','📎',4,5),
  F("Romance",1999,"Catherine Breillat",['90s','psychosexual','dark','unwatchable','romantic'],'desire dissected without anesthesia','🛏',5,4),
  F("Anatomy of Hell",2004,"Catherine Breillat",['2000s','psychosexual','unwatchable','philosophical','dark'],'sexual politics as ordeal','🕳',5,3),
  F("Trouble Every Day",2001,"Claire Denis",['2000s','psychosexual','body-horror','dream','dark'],'carnal hunger in soft focus','🩸',5,4),
  F("Dogs Don't Wear Pants",2019,"J-P Valkeapää",['2010s','psychosexual','dark','beautiful-damage','tender'],'grief finds a leather collar','🖤',4,5),
  F("Sanctuary",2022,"Zachary Wigon",['2020s','psychosexual','playful','dark','dialogue'],'hotel-room power-game chess','♟',4,5),
  F("The Night Porter",1974,"Liliana Cavani",['70s','psychosexual','dark','unwatchable','historical'],'trauma and erotic power loop','🧤',4,4),
  F("Swimming Pool",2003,"François Ozon",['2000s','psychosexual','mystery','dream','stylish'],'sunlit writerly erotic ambiguity','🏊',4,5),

  // US underground, punk, downtown, cult
  F("Pink Flamingos",1972,"John Waters",['70s','underground','campy','macabre','unwatchable'],'filth as competitive art form','🦩',5,4),
  F("Female Trouble",1974,"John Waters",['70s','underground','campy','crime','macabre'],'crime-beauty pageant depravity','💄',5,5),
  F("Desperate Living",1977,"John Waters",['70s','underground','campy','macabre','weird'],'garbage-kingdom fairy tale','👑',5,4),
  F("Multiple Maniacs",1970,"John Waters",['70s','underground','campy','macabre','weird'],'Catholic lobster-show blasphemy','🦞',5,4),
  F("Liquid Sky",1982,"Slava Tsukerman",['80s','underground','night-city','cyber','campy','psychosexual'],'New Wave alien heroin neon','👾',5,4),
  F("Decoder",1984,"Muscha",['80s','underground','counterculture','cyber','esoteric'],'industrial sound terrorism conspiracy','📼',5,3),
  F("Smithereens",1982,"Susan Seidelman",['80s','counterculture','night-city','underground','beautiful-damage'],'downtown punk social-climbing ache','🧷',5,4),
  F("Variety",1983,"Bette Gordon",['80s','night-city','psychosexual','underground','crime'],'Times Square voyeur noir','🎟',5,4),
  F("Born in Flames",1983,"Lizzie Borden",['80s','counterculture','political','underground','kinetic'],'feminist pirate-radio insurgency','📻',5,5),
  F("Times Square",1980,"Allan Moyle",['80s','counterculture','night-city','tender-weirdos','music'],'runaway girls on punk Manhattan','🎤',5,4),
  F("Downtown 81",2000,"Edo Bertoglio",['2000s','night-city','art','counterculture','music'],'Basquiat wanders downtown mythology','🎨',5,4),
  F("Permanent Vacation",1980,"Jim Jarmusch",['80s','lonely','night-city','underground','liminal'],'downtown drifting before the style hardened','🧳',5,4),
  F("Mystery Train",1989,"Jim Jarmusch",['80s','night-city','tender-weirdos','playful','liminal'],'Memphis motel intersecting loneliness','🚂',5,5),
  F("Rubin & Ed",1991,"Trent Harris",['90s','tender-weirdos','weird','comedy','underground'],'desert cat-burial anti-buddy odyssey','🐈',5,4),
  F("Out of the Blue",1980,"Dennis Hopper",['80s','counterculture','dark','beautiful-damage','angry'],'punk child in a wrecked family','🚚',5,4),
  F("River's Edge",1986,"Tim Hunter",['80s','dark','counterculture','beautiful-damage','crime'],'teen nihilism beside a corpse','🌊',5,4),
  F("Street Trash",1987,"J. Michael Muro",['80s','c-films','macabre','campy','body-horror'],'melt-movie gutter splatter','🧪',4,3),
  F("Basket Case",1982,"Frank Henenlotter",['80s','c-films','underground','body-horror','campy'],'Times Square mutant brotherhood','🧺',5,4),
  F("Brain Damage",1988,"Frank Henenlotter",['80s','c-films','body-horror','night-city','campy'],'parasite addiction puppet show','🪱',5,4),
  F("Frankenhooker",1990,"Frank Henenlotter",['90s','c-films','campy','body-horror','night-city'],'purple-crack Frankenstein sleaze','⚡',5,4),
  F("Society",1989,"Brian Yuzna",['80s','body-horror','campy','macabre','c-films'],'Beverly Hills class shunting','🫠',5,4),
  F("Hardware",1990,"Richard Stanley",['90s','cyber','end-times','c-films','night-city'],'apartment robot siege grime','🤖',5,3),
  F("Dust Devil",1992,"Richard Stanley",['90s','esoteric','horror','desert','dream'],'Namibian occult road nightmare','🌪',5,4),
  F("Prayer of the Rollerboys",1990,"Rick King",['90s','y2k','c-films','counterculture','cyber'],'rollerblade fascist youth dystopia','🛼',5,2),
  F("Freejack",1992,"Geoff Murphy",['90s','cyber','c-films','kinetic','y2k'],'future-body-snatch corporate cheese','⏩',4,3),
  F("Nemesis",1992,"Albert Pyun",['90s','cyber','c-films','kinetic','rocket-fuel'],'cyborg gunfire maximalism','🦿',5,3),

  // liminal, dream, uncanny, occult
  F("Carnival of Souls",1962,"Herk Harvey",['60s','liminal','horror','dream','lonely'],'abandoned-pavilion afterlife drift','🎠',5,4),
  F("Messiah of Evil",1973,"Willard Huyck, Gloria Katz",['70s','horror','liminal','night-city','esoteric'],'California seaside art-zombie trance','🌊',5,4),
  F("Let's Scare Jessica to Death",1971,"John D. Hancock",['70s','horror','dream','psychological','liminal'],'country-house uncertain vampirism','🧛',5,4),
  F("Images",1972,"Robert Altman",['70s','dream','psychological','liminal','dark'],'identity dissolves in rural mirrors','🪞',5,4),
  F("3 Women",1977,"Robert Altman",['70s','dream','identity','liminal','beautiful-damage'],'desert personalities bleed together','🏜',5,5),
  F("The Reflecting Skin",1990,"Philip Ridley",['90s','dream','macabre','beautiful-damage','gothic'],'sunlit prairie childhood nightmare','🌻',5,4),
  F("Institute Benjamenta",1995,"Stephen Quay, Timothy Quay",['90s','dream','liminal','esoteric','underground'],'black-and-white school of submission','🪜',5,4),
  F("Alice",1988,"Jan Švankmajer",['80s','dream','macabre','experimental','weird'],'taxidermy Wonderland menace','🐇',5,5),
  F("Conspirators of Pleasure",1996,"Jan Švankmajer",['90s','psychosexual','weird','underground','playful'],'private rituals become machinery','🧤',5,4),
  F("Little Otik",2000,"Jan Švankmajer",['2000s','macabre','weird','folk','body-horror'],'wooden baby appetite fairy tale','🪵',5,4),
  F("Faust",1994,"Jan Švankmajer",['90s','esoteric','weird','experimental','macabre'],'puppet occult bargain nightmare','🎭',5,4),
  F("The Wolf House",2018,"Cristóbal León, Joaquín Cociña",['2010s','experimental','horror','dream','underground'],'stop-motion walls mutate around you','🐺',5,4),
  F("The Forbidden Room",2015,"Guy Maddin, Evan Johnson",['2010s','dream','experimental','playful','esoteric'],'lost-film fever anthology','🚪',5,4),
  F("Careful",1992,"Guy Maddin",['90s','dream','campy','gothic','weird'],'mountain melodrama under avalanche law','🏔',5,4),
  F("The Saddest Music in the World",2003,"Guy Maddin",['2000s','campy','dream','music','macabre'],'beer baroness grief contest','🍺',5,4),
  F("Brand Upon the Brain!",2006,"Guy Maddin",['2000s','dream','experimental','macabre','kinetic'],'silent-film orphanage psychodrama','🧠',5,4),
  F("Phase IV",1974,"Saul Bass",['70s','cosmic','liminal','philosophical','horror'],'ants achieve geometric transcendence','🐜',5,4),
  F("Seconds",1966,"John Frankenheimer",['60s','identity','paranoid','dark','brainfuck'],'suburban rebirth becomes terror','👤',5,5),
  F("The Quiet Earth",1985,"Geoff Murphy",['80s','end-times','cosmic','lonely','philosophical'],'three people after reality empties','🌅',5,4),
  F("The Lathe of Heaven",1980,"Fred Barzyk, David Loxton",['80s','philosophical','dream','cosmic','brainfuck'],'dreams rewrite public reality','🛌',5,4),
  F("World on a Wire",1973,"Rainer Werner Fassbinder",['70s','cyber','philosophical','brainfuck','paranoid'],'simulation theory in glass offices','🖥',5,4),

  // crime / pressure / night city
  F("Mikey and Nicky",1976,"Elaine May",['70s','crime','night-city','tender','beautiful-damage'],'friendship panics through one bad night','🚕',5,5),
  F("The Friends of Eddie Coyle",1973,"Peter Yates",['70s','crime','dark','night-city','tender'],'Boston low-level criminal fatalism','🔫',5,4),
  F("The Killing of a Chinese Bookie",1976,"John Cassavetes",['70s','crime','night-city','beautiful-damage','slow'],'nightclub owner walks into debt noir','🎰',5,4),
  F("Straight Time",1978,"Ulu Grosbard",['70s','crime','dark','beautiful-damage','angry'],'parole curdles back into robbery','⌚',5,4),
  F("Blue Collar",1978,"Paul Schrader",['70s','crime','angry','political','dark'],'factory workers cornered by the system','🔧',5,4),
  F("The Driver",1978,"Walter Hill",['70s','crime','night-city','kinetic','stylish'],'pure getaway-car geometry','🚘',5,4),
  F("To Live and Die in L.A.",1985,"William Friedkin",['80s','crime','kinetic','night-city','elegant-panic'],'counterfeit neon moral freefall','💵',5,5),
  F("King of New York",1990,"Abel Ferrara",['90s','crime','night-city','dark','stylish'],'drug-kingpin nocturnal opera','👑',5,4),
  F("Bad Lieutenant",1992,"Abel Ferrara",['90s','crime','dark','unwatchable','beautiful-damage'],'Catholic cop self-annihilation','✝',5,4),
  F("Light Sleeper",1992,"Paul Schrader",['90s','night-city','crime','lonely','beautiful-damage'],'drug courier keeps nocturnal diary','🌙',5,5),
  F("One False Move",1992,"Carl Franklin",['90s','crime','dark','kinetic','tender'],'small-town crime fuse burns inward','🛣',5,4),
  F("Deep Cover",1992,"Bill Duke",['90s','crime','night-city','stylish','dark'],'undercover identity in neon L.A.','🕶',5,5),
  F("Miami Vice",2006,"Michael Mann",['2000s','night-city','crime','romantic','stylish'],'digital-night speedboat melancholy','🚤',5,5),

  // documentaries: obsessive, strange, alive
  F("Hands on a Hardbody: The Documentary",1997,"S.R. Bindler",['90s','documentary','docs-weird','tender-weirdos','americana'],'Texans outlast each other for a truck','🛻',5,5),
  F("Sherman's March",1986,"Ross McElwee",['80s','documentary','tender-weirdos','romantic','playful'],'Civil War project becomes dating diary','📹',5,4),
  F("Vernon, Florida",1981,"Errol Morris",['80s','documentary','docs-weird','tender-weirdos','americana'],'Florida eccentrics talk reality sideways','🦃',5,5),
  F("Gates of Heaven",1978,"Errol Morris",['70s','documentary','docs-weird','tender','philosophical'],'pet cemeteries become metaphysics','🐕',5,5),
  F("Fast, Cheap & Out of Control",1997,"Errol Morris",['90s','documentary','docs-inspire','weird','philosophical'],'four obsessions rhyme by accident','🤖',5,5),
  F("The Emperor's Naked Army Marches On",1987,"Kazuo Hara",['80s','documentary','unwatchable','angry','political'],'war crimes confronted at the doorstep','🎖',5,4),
  F("Harlan County War",2000,"Tony Buba",['2000s','documentary','angry','political','americana'],'labor conflict on the ground','⛏',4,4),
  F("Grey Gardens",1975,"Albert Maysles, David Maysles, Ellen Hovde, Muffie Meyer",['70s','documentary','docs-weird','tender-weirdos','beautiful-damage'],'decaying mansion mother-daughter universe','🏚',5,5),
  F("Streetwise",1984,"Martin Bell",['80s','documentary','dark','tender','beautiful-damage'],'Seattle street kids without varnish','🛣',5,4),
  F("Titicut Follies",1967,"Frederick Wiseman",['60s','documentary','unwatchable','dark','institutional'],'institutional horror without narration','🏥',5,4),
  F("The Cruise",1998,"Bennett Miller",['90s','documentary','tender-weirdos','night-city','philosophical'],'eccentric NYC tour guide cosmology','🚌',5,5),
  F("Dark Days",2000,"Marc Singer",['2000s','documentary','underground','tender','night-city'],'community living beneath Manhattan','🚇',5,5),
  F("DIG!",2004,"Ondi Timoner",['2000s','documentary','music','beautiful-damage','counterculture'],'rock friendship and ego slow-motion crash','🎸',5,4),
  F("The Devil and Daniel Johnston",2005,"Jeff Feuerzeig",['2000s','documentary','music','tender','beautiful-damage'],'outsider art, love, and instability','📼',5,5),
  F("American Movie",1999,"Chris Smith",['90s','documentary','tender-weirdos','docs-inspire','playful'],'Wisconsin filmmaker refuses to quit','🎬',5,5),
  F("Project Grizzly",1996,"Peter Lynch",['90s','documentary','docs-weird','tender-weirdos','obsession'],'man builds bear-proof armor','🐻',5,4),
  F("The King of Kong: A Fistful of Quarters",2007,"Seth Gordon",['2000s','documentary','playful','obsession','tender-weirdos'],'arcade-score rivalry as western','🕹',4,5),
  F("Marwencol",2010,"Jeff Malmberg",['2010s','documentary','tender-weirdos','docs-inspire','art'],'miniature world rebuilds a life','📷',5,5),
  F("The Wolfpack",2015,"Crystal Moselle",['2010s','documentary','cinema','tender-weirdos','beautiful-damage'],'isolated brothers recreate movies at home','🎭',5,5),
  F("Tickled",2016,"David Farrier, Dylan Reeve",['2010s','documentary','docs-weird','dark','brainfuck'],'competitive tickling opens a trapdoor','🪶',5,4),
  F("The Imposter",2012,"Bart Layton",['2010s','documentary','brainfuck','crime','dark'],'identity fraud becomes family nightmare','🪪',4,5),

  // cult rocket fuel / maximalist oddities
  F("Phantom of the Paradise",1974,"Brian De Palma",['70s','campy','music','macabre','kinetic'],'glam-rock Faust in chrome','🎹',5,5),
  F("Streets of Fire",1984,"Walter Hill",['80s','night-city','music','kinetic','campy'],'rock-and-roll fable under neon rain','🔥',5,5),
  F("Night of the Comet",1984,"Thom Eberhardt",['80s','end-times','campy','playful','night-city'],'mall-girl apocalypse bubblegum','☄',5,5),
  F("The Hidden",1987,"Jack Sholder",['80s','crime','sci-fi','kinetic','campy'],'alien parasite police chase rocket','👽',5,4),
  F("Split Second",1992,"Tony Maylam",['90s','c-films','night-city','sci-fi','campy'],'flooded London monster cop sludge','🌧',4,3),
  F("Until the End of the World",1991,"Wim Wenders",['90s','road','cyber','romantic','cosmic'],'global road movie into dream technology','🌍',5,5),
  F("Brainstorm",1983,"Douglas Trumbull",['80s','cyber','philosophical','cosmic','brainfuck'],'recorded consciousness as corporate weapon','🧠',5,4),
  F("Altered States",1980,"Ken Russell",['80s','body-horror','cosmic','psychosexual','brainfuck'],'sensory-deprivation evolutionary meltdown','🧬',5,4),
  F("Colossus: The Forbin Project",1970,"Joseph Sargent",['70s','cyber','paranoid','philosophical','end-times'],'cold-war AI quietly takes charge','💻',5,4)
];

for (const film of V04_CURATED) {
  if (!FILMS.some(existing => existing.title === film.title && existing.year === film.year)) FILMS.push(film);
}
