/*
  JL²GETHER seed catalogue.
  The app is designed to enrich poster/director/synopsis data lazily from Cinemeta.
  Letterboxd account exports can be imported locally by each viewer; those files never leave the browser.
*/

const PROFILE_SEEDS = {
  josh: {
    label: 'Joshie', alias: 'Bubble', weight: 1,
    favorites: ['The Man from Earth','Napoleon Dynamite','Lost in Translation','The Holy Mountain','Eraserhead','Stalker','Trainspotting','Before Sunrise','Gummo','The Matrix','Hackers','Run Lola Run'],
    taste: { liminal:5, metaphysical:5, underground:5, weird:5, '90s':5, y2k:5, kinetic:4, dream:5, counterculture:5, documentary:4, romantic:2, comedy:2, horror:3, psychosexual:3, cyber:4, tender:3, macabre:4 }
  },
  julie: {
    label: 'Julie', alias: 'Birdie', weight: 1,
    favorites: ['Dead Poets Society','The Grand Budapest Hotel','City of God','Good Time','Being John Malkovich','The Matrix','Wild at Heart','Fantastic Mr. Fox','Raw','Run Lola Run','Go','Requiem for a Dream'],
    taste: { emotional:5, kinetic:5, dark:4, playful:4, stylish:5, weird:4, crime:4, romantic:3, comedy:4, horror:4, dream:3, y2k:3, '90s':3, tender:4, macabre:4, surreal:4 }
  }
};

const MOODS = [
  ['bored','Bored','🧨','Give me a reason to look up from the void.'],
  ['restless','Restless','⚡','Movement, velocity, pressure, no dead air.'],
  ['sleepy','Sleepy','🌒','Slow, strange, soft-edged, maybe half-dreamed.'],
  ['horny','Horny','🫦','Sensual, charged, psychosexual, desirous.'],
  ['in-love','In love','♥','Intimacy, chemistry, tenderness, ache.'],
  ['weirded-out','Weirded out','🫥','Something is wrong with the room. Good.'],
  ['homesick','Homesick','🏠','Comfort, repeats, family classics, private nostalgia.'],
  ['depressed','Depressed','☂','Something honest enough to sit beside you.'],
  ['playful','Playful','🎈','Inventive, mischievous, ridiculous in the right way.'],
  ['harmonious','Harmonious','◌','Quietly beautiful films that settle the static.'],
  ['nostalgic','Nostalgic','📼','Personal memory first; age of the movie second.'],
  ['philosophical','Philosophical','∞','Existence, consciousness, morality, time.'],
  ['curious','Curious','🔎','A door you didn’t know was there.'],
  ['afraid','Afraid','🕯','Fear that gets under the skin rather than just yelling.'],
  ['macabre','Macabre','⚰','Death, rot, gothic beauty, black humor.'],
  ['wired','Wired','📡','Neon nervous system. More input.'],
  ['lonely','Lonely','🌃','Company for the beautifully disconnected.'],
  ['cosmic','Cosmic','🪐','Make the world feel enormous and strange.'],
  ['angry','Angry','⛓','Catharsis, rebellion, systems getting kicked.'],
  ['tender','Tender','🫀','Fragile humans trying very hard.'],
  ['campy','Campy','💄','Committed excess. No apology.']
];

const VIBES = [
  ['25th-hour','The 25th Hour','🌘','Hypnagogic cinema for when the night has gone one hour too far.'],
  ['unwatchable','Unwatchable','⛓','Great films with a built-in dare: duration, violence, abrasion or psychic punishment.'],
  ['c-films','C-Films','🥃','Low-rated cult wreckage, accidental genius and glorious bad decisions.'],
  ['y2k-club','90s / Y2K Club Fever','💿','Trip-hop, techno, cigarettes, warehouse nights and pre-millennial electricity.'],
  ['90s-kinetic','90s Kinetic Weirdness','🛼','The decade moving too fast: grunge, panic, video texture, strange youth.'],
  ['70s-rocket','High-Energy 70s','🚬','Sweat, engines, paranoia and grown adults making catastrophically committed choices.'],
  ['liminal','Liminal Cinema','🚪','Thresholds, empty spaces, waiting rooms between realities.'],
  ['dream-logic','Dream Logic','🪞','Images obey emotional physics instead of ordinary causality.'],
  ['rocket-fuel','Rocket Fuel','🚀','Movies that make your bloodstream feel carbonated.'],
  ['brainfuck','WTF / Brainfuck','🧠','Reality folds, then keeps folding after the credits.'],
  ['esoteric','Weird / Esoteric / Underground','🜏','Occult frequencies, strange subcultures, handmade worlds.'],
  ['docs-inspire','Documentaries That Switch You On','🗺','Wonder, obsession, landscape, craft, scale.'],
  ['docs-weird','Weird Documentaries','🦴','True stories from parts of reality that seem fictional.'],
  ['underground-art','Underground Arthouse','🕳','Personal, abrasive, beautiful work from outside the clean rooms.'],
  ['night-city','Night City','🌃','Streetlights, loneliness, convenience stores, taxis and after-hours selves.'],
  ['beautiful-damage','Beautifully Damaged','🥀','People are a mess; the movie knows exactly how beautiful that can be.'],
  ['tender-weirdos','Tender Weirdos','🧃','Odd people loved without sanding off their oddness.'],
  ['end-times','End of the World at 3AM','📺','Millennial dread, broadcasts, empty streets and existential static.'],
  ['elegant-panic','Elegant Panic','🩸','Stress, style and forward motion with a pulse you can dance to.']
];

const DECADES = ['1920s','1930s','1940s','1950s','1960s','1970s','1980s','1990s','2000s','2010s','2020s'];

const DIRECTOR_SEEDS = {
  josh: ['David Lynch','Andrei Tarkovsky','Werner Herzog','Gregg Araki','David Cronenberg','Richard Linklater','Wong Kar-wai','Harmony Korine','Alejandro Jodorowsky','Danny Boyle','Shinya Tsukamoto','Gaspar Noé'],
  julie: ['Wes Anderson','David Fincher','Bong Joon Ho','Safdie Brothers','Miloš Forman','David Lynch','Julia Ducournau','Christopher Nolan','Edgar Wright','Martin Scorsese','Park Chan-wook','Paul Thomas Anderson'],
  both: ['David Lynch','Wes Anderson','Danny Boyle','Bong Joon Ho','Gregg Araki','David Cronenberg','Safdie Brothers','Wong Kar-wai','Werner Herzog','Paul Thomas Anderson','Park Chan-wook','Shinya Tsukamoto']
};

const SIMILAR_ANCHORS = {
  josh: ['Eraserhead','Stalker','The Holy Mountain','Trainspotting','Lost in Translation','Napoleon Dynamite','The Man from Earth','Before Sunrise','Gummo','The Matrix','Hackers','Run Lola Run','Nowhere','eXistenZ','Koyaanisqatsi','Mysterious Skin','Buffalo ’66','Pi','The Doom Generation','Fallen Angels','The Rocky Horror Picture Show','There Will Be Blood','Into the Wild','Night of the Living Dead','Everything Everywhere All at Once','Strange Days'],
  julie: ['Dead Poets Society','The Grand Budapest Hotel','City of God','Good Time','Amadeus','Being John Malkovich','The Matrix','Wild at Heart','Fantastic Mr. Fox','Raw','Run Lola Run','Go','Requiem for a Dream','The Big Lebowski','Whiplash','Spirited Away','Titane','The Apartment','Snatch','Baby Driver','The Shining','The Prestige','The Hunt','Moonlight','Enter the Void','Roman Holiday'],
  both: ['Run Lola Run','The Matrix','Napoleon Dynamite','Dead Poets Society','Go','The Holy Mountain','Midsommar','Being John Malkovich','Good Time','City of God','Trainspotting','The Grand Budapest Hotel','Wild at Heart','Fantastic Mr. Fox','Lost in Translation','Eraserhead','Raw','The Big Lebowski','Hackers','Enter the Void','Before Sunrise','Requiem for a Dream','Koyaanisqatsi','Whiplash','Nowhere','The Shining']
};

function F(title, year, director, tags, vibe, emoji='•', j=0, u=0, extra={}) {
  return { title, year, director, tags, vibe, emoji, affinity:{josh:j,julie:u}, ...extra };
}

const FILMS = [
  // 90s / Y2K club & kinetic
  F('Hackers',1995,'Iain Softley',['90s','y2k','cyber','kinetic','playful','night-city','y2k-club'],'neon rollerblade rebellion','💿',5,3,{slug:'hackers'}),
  F('Run Lola Run',1998,'Tom Tykwer',['90s','kinetic','romantic','elegant-panic','rocket-fuel','y2k-club'],'techno destiny sprint','🏃',5,5,{slug:'run-lola-run'}),
  F('Trainspotting',1996,'Danny Boyle',['90s','counterculture','kinetic','dark','y2k-club','beautiful-damage'],'filthy velocity','🚽',5,4,{slug:'trainspotting'}),
  F('Nowhere',1997,'Gregg Araki',['90s','underground','weird','surreal','night-city','y2k-club'],'queer alien apocalypse','👽',5,4,{slug:'nowhere'}),
  F('The Doom Generation',1995,'Gregg Araki',['90s','underground','counterculture','weird','dark','psychosexual'],'nihilistic road candy','🧨',5,3),
  F('Go',1999,'Doug Liman',['90s','y2k','kinetic','crime','playful','night-city','y2k-club'],'rave-night pinball','💊',5,5,{slug:'go'}),
  F('Human Traffic',1999,'Justin Kerrigan',['90s','y2k','kinetic','playful','y2k-club','night-city'],'weekend rave bloodstream','🔊',5,4),
  F('Groove',2000,'Greg Harrison',['y2k','kinetic','y2k-club','night-city','tender'],'warehouse sunrise','🪩',4,3),
  F('Clubbed to Death',1996,'Yolande Zauberman',['90s','y2k-club','night-city','dark','romantic'],'after-hours narcotic drift','🌫',5,3),
  F('Shopping',1994,'Paul W. S. Anderson',['90s','counterculture','kinetic','crime','y2k-club'],'joyride industrial youth','🛞',4,2),
  F('Belly',1998,'Hype Williams',['90s','stylish','crime','night-city','y2k-club'],'blacklight street opera','🔵',4,4),
  F('Love & Pop',1998,'Hideaki Anno',['90s','y2k','weird','experimental','night-city','tender'],'consumer-tech adolescence','☎',5,3),
  F('SLC Punk!',1998,'James Merendino',['90s','counterculture','kinetic','comedy','tender'],'punk identity meltdown','🧷',5,3),
  F('Strange Days',1995,'Kathryn Bigelow',['90s','y2k','cyber','night-city','dark','end-times'],'millennial sensory panic','📼',4,4),
  F('Johnny Mnemonic',1995,'Robert Longo',['90s','cyber','y2k','campy','kinetic'],'data-smuggler chrome fever','🧠',4,2),
  F('Nirvana',1997,'Gabriele Salvatores',['90s','cyber','y2k','night-city','philosophical'],'European cyber melancholy','🖥',4,2),
  F('Brainscan',1994,'John Flynn',['90s','cyber','horror','y2k','night-city'],'bedroom-tech nightmare','🕹',3,2),
  F('Virtuosity',1995,'Brett Leonard',['90s','cyber','campy','kinetic'],'VR serial-killer gloss','🕶',3,2),
  F('The Faculty',1998,'Robert Rodriguez',['90s','horror','kinetic','playful'],'alt-kid body-snatcher rush','👟',3,3),
  F('Freeway',1996,'Matthew Bright',['90s','underground','dark','comedy','kinetic'],'trash-fable ferocity','🛣',4,3),
  F('Natural Born Killers',1994,'Oliver Stone',['90s','kinetic','experimental','dark','brainfuck'],'media-age hallucination','📺',4,3),
  F('The Acid House',1998,'Paul McGuigan',['90s','weird','counterculture','dark','y2k-club'],'chemical Scottish grotesque','🧪',4,2),
  F('Tokyo Fist',1995,'Shinya Tsukamoto',['90s','kinetic','underground','dark','experimental'],'urban flesh impact','🥊',5,3),
  F('Bullet Ballet',1998,'Shinya Tsukamoto',['90s','underground','dark','night-city','beautiful-damage'],'gunmetal grief','🔫',5,3),
  F('Tetsuo II: Body Hammer',1992,'Shinya Tsukamoto',['90s','cyber','kinetic','underground','body'],'flesh-machine rage','⚙',5,2),
  F('Pi',1998,'Darren Aronofsky',['90s','brainfuck','philosophical','dark','experimental'],'math-mystic migraine','π',5,3),
  F('Buffalo ’66',1998,'Vincent Gallo',['90s','romantic','weird','tender','beautiful-damage'],'hostile sad-boy tenderness','🎳',5,3),
  F('All Over Me',1997,'Alex Sichel',['90s','underground','tender','night-city','romantic'],'queer summer bruises','🖤',4,3),
  F('Mod Fuck Explosion',1994,'Jon Moritsugu',['90s','underground','counterculture','weird'],'handmade teen detonation','💥',5,2),
  F('Terminal USA',1993,'Jon Moritsugu',['90s','underground','campy','weird'],'suburban video mutiny','📹',4,3),
  F('Party Girl',1995,'Daisy von Scherler Mayer',['90s','playful','night-city','y2k-club'],'downtown fashion bounce','👜',3,4),

  // dream / liminal / 25th hour
  F('Eraserhead',1977,'David Lynch',['liminal','dream','macabre','underground','25th-hour'],'industrial sleep paralysis','🕳',5,3),
  F('Stalker',1979,'Andrei Tarkovsky',['liminal','philosophical','slow','25th-hour','metaphysical'],'sacred-zone drift','🌾',5,2),
  F('Mirror',1975,'Andrei Tarkovsky',['liminal','dream','philosophical','tender'],'memory as weather','🪞',5,3),
  F('Nostalghia',1983,'Andrei Tarkovsky',['liminal','philosophical','homesick','slow'],'exile in candlelight','🕯',5,2),
  F('Solaris',1972,'Andrei Tarkovsky',['liminal','philosophical','cosmic','dream'],'grief orbiting a planet','🌊',5,3),
  F('Last Year at Marienbad',1961,'Alain Resnais',['liminal','dream','brainfuck','romantic','25th-hour'],'memory maze in formalwear','♟',5,2),
  F('3 Women',1977,'Robert Altman',['liminal','dream','weird','tender'],'identity melting in desert light','🌵',5,4),
  F('Picnic at Hanging Rock',1975,'Peter Weir',['liminal','dream','macabre','25th-hour'],'sunlit disappearance spell','🌿',4,4),
  F('The Double Life of Véronique',1991,'Krzysztof Kieślowski',['liminal','romantic','dream','tender','90s'],'two lives breathing together','🟢',5,4),
  F('Dead Man',1995,'Jim Jarmusch',['90s','liminal','western','philosophical','25th-hour'],'acid western purgatory','🚂',4,3),
  F('Gerry',2002,'Gus Van Sant',['liminal','slow','unwatchable','philosophical'],'desert time dissolving','🏜',4,2),
  F('Uncle Boonmee Who Can Recall His Past Lives',2010,'Apichatpong Weerasethakul',['liminal','dream','metaphysical','tender'],'jungle ghosts at dinner','🐒',5,3),
  F('Tropical Malady',2004,'Apichatpong Weerasethakul',['liminal','dream','romantic','weird'],'love becoming jungle myth','🐅',5,3),
  F('Memoria',2021,'Apichatpong Weerasethakul',['liminal','cosmic','slow','philosophical'],'a sound opening reality','🫧',5,3),
  F('The Turin Horse',2011,'Béla Tarr',['liminal','slow','unwatchable','philosophical'],'the world running out','🌬',4,2),
  F('La Jetée',1962,'Chris Marker',['liminal','philosophical','brainfuck','romantic'],'memory after apocalypse','🖼',5,3),
  F('The Bothersome Man',2006,'Jens Lien',['liminal','weird','brainfuck','dark'],'perfect life with no pulse','🧱',5,4),
  F('Burning',2018,'Lee Chang-dong',['liminal','mystery','dark','tender'],'absence glowing like an ember','🔥',4,4),
  F('Inland Empire',2006,'David Lynch',['dream','brainfuck','25th-hour','unwatchable','night-city'],'three-hour identity fever','🐇',5,3),
  F('Carnival of Souls',1962,'Herk Harvey',['25th-hour','liminal','macabre','dream'],'organ-music afterlife','🎡',4,3),
  F('Messiah of Evil',1973,'Willard Huyck',['25th-hour','macabre','dream','weird'],'empty-coast nightmare pop','🩸',4,3),
  F('Valerie and Her Week of Wonders',1970,'Jaromil Jireš',['dream','macabre','esoteric','25th-hour'],'fairytale puberty séance','🕊',5,3),
  F('Angel’s Egg',1985,'Mamoru Oshii',['dream','liminal','25th-hour','cosmic'],'gothic animated sleep-state','🥚',5,3),
  F('The Hourglass Sanatorium',1973,'Wojciech Jerzy Has',['dream','esoteric','25th-hour','liminal'],'baroque time labyrinth','⌛',5,3),
  F('Institute Benjamenta',1995,'Stephen Quay, Timothy Quay',['90s','dream','underground','25th-hour','liminal'],'dusty ritual school','🗝',5,2),
  F('The Wolf House',2018,'Cristóbal León, Joaquín Cociña',['dream','macabre','underground','weird'],'walls mutating around trauma','🐺',5,3),
  F('Belladonna of Sadness',1973,'Eiichi Yamamoto',['dream','psychosexual','esoteric','macabre'],'watercolor erotic nightmare','🌺',4,3),
  F('The Color of Pomegranates',1969,'Sergei Parajanov',['dream','esoteric','liminal','philosophical'],'icons arranged like memory','🍎',5,3),
  F('Meshes of the Afternoon',1943,'Maya Deren',['dream','liminal','underground','brainfuck'],'the original dream loop','🔑',5,3),
  F('Black Moon',1975,'Louis Malle',['dream','weird','esoteric'],'surreal civil-war fairytale','🦄',4,2),
  F('The Saragossa Manuscript',1965,'Wojciech Jerzy Has',['dream','brainfuck','esoteric','playful'],'stories nesting into infinity','📜',5,3),

  // brainfuck / metaphysical
  F('The Matrix',1999,'Lana Wachowski, Lilly Wachowski',['90s','y2k','cyber','philosophical','kinetic','brainfuck'],'reality with a trapdoor','🟩',5,5),
  F('eXistenZ',1999,'David Cronenberg',['90s','y2k','cyber','brainfuck','body','weird'],'flesh-console reality leak','🎮',5,3),
  F('Videodrome',1983,'David Cronenberg',['brainfuck','body','cyber','macabre','esoteric'],'media becoming flesh','📺',5,4),
  F('Crash',1996,'David Cronenberg',['90s','psychosexual','body','dark','esoteric'],'desire welded to metal','🚗',5,4),
  F('Primer',2004,'Shane Carruth',['brainfuck','philosophical','indie'],'time travel as engineering notebook','⏱',5,3),
  F('Upstream Color',2013,'Shane Carruth',['brainfuck','liminal','romantic','dream'],'love after identity contamination','🐖',5,3),
  F('Coherence',2013,'James Ward Byrkit',['brainfuck','philosophical','thriller'],'dinner party multiverse fracture','☄',4,4),
  F('Timecrimes',2007,'Nacho Vigalondo',['brainfuck','kinetic','dark'],'time loop tightening like wire','🕳',4,4),
  F('Enemy',2013,'Denis Villeneuve',['brainfuck','dream','dark','psychosexual'],'double-self spider dread','🕷',4,5),
  F('Predestination',2014,'Michael Spierig, Peter Spierig',['brainfuck','philosophical','thriller'],'identity folded through time','♾',4,3),
  F('Possessor',2020,'Brandon Cronenberg',['brainfuck','body','dark','cyber'],'assassination by borrowed body','🧬',4,4),
  F('Sorry to Bother You',2018,'Boots Riley',['brainfuck','surreal','comedy','angry'],'capitalism mutates on camera','☎',4,4),
  F('Dogtooth',2009,'Yorgos Lanthimos',['brainfuck','weird','dark','underground'],'family reality as prison','🦷',5,4),
  F('Holy Motors',2012,'Leos Carax',['brainfuck','dream','esoteric','playful'],'cinema changing costumes','🚘',5,3),
  F('Synecdoche, New York',2008,'Charlie Kaufman',['brainfuck','philosophical','depressed','tender'],'life becoming an endless rehearsal','🏙',5,4),
  F('World on a Wire',1973,'Rainer Werner Fassbinder',['brainfuck','philosophical','cyber','70s'],'simulation theory in smoked glass','🪟',5,2),
  F('Beyond the Infinite Two Minutes',2020,'Junta Yamaguchi',['brainfuck','playful','kinetic'],'two-minute future slapstick','📹',4,4),
  F('One Cut of the Dead',2017,'Shinichirō Ueda',['brainfuck','playful','kinetic','tender'],'a filmmaking trick with a huge heart','🎥',4,5),
  F('The Congress',2013,'Ari Folman',['brainfuck','cyber','dream','philosophical'],'identity sold into animation','💊',4,3),

  // rocket fuel / high energy
  F('Good Time',2017,'Josh Safdie, Benny Safdie',['kinetic','crime','night-city','elegant-panic','rocket-fuel'],'one bad night accelerating','🟣',4,5),
  F('Uncut Gems',2019,'Josh Safdie, Benny Safdie',['kinetic','crime','elegant-panic','rocket-fuel'],'anxiety with a diamond core','💎',4,5),
  F('Crank',2006,'Mark Neveldine, Brian Taylor',['kinetic','campy','rocket-fuel'],'pure poisoned velocity','💉',3,4),
  F('Mad Max: Fury Road',2015,'George Miller',['kinetic','rocket-fuel','action'],'two hours of forward motion','🔥',4,5),
  F('Victoria',2015,'Sebastian Schipper',['kinetic','crime','night-city','elegant-panic'],'one-take Berlin descent','🌃',4,4),
  F('Climax',2018,'Gaspar Noé',['kinetic','night-city','dark','psychosexual','elegant-panic'],'dancefloor hell spiral','💃',5,4),
  F('Athena',2022,'Romain Gavras',['kinetic','angry','rocket-fuel'],'riot as tragic choreography','🔥',4,4),
  F('Point Break',1991,'Kathryn Bigelow',['90s','kinetic','action','playful'],'surf-crime adrenaline mysticism','🏄',4,4),
  F('Speed',1994,'Jan de Bont',['90s','kinetic','action','rocket-fuel'],'clean mechanical suspense','🚌',3,4),
  F('The Raid',2011,'Gareth Evans',['kinetic','action','rocket-fuel'],'vertical combat furnace','🥋',3,5),
  F('The Raid 2',2014,'Gareth Evans',['kinetic','action','rocket-fuel','crime'],'operatic impact machine','🔨',3,5),
  F('City of God',2002,'Fernando Meirelles, Kátia Lund',['kinetic','crime','dark','emotional'],'street history at bullet speed','📸',4,5),
  F('Baby Driver',2017,'Edgar Wright',['kinetic','crime','playful','rocket-fuel'],'getaway driving on a mixtape','🎧',3,5),
  F('Snatch',2000,'Guy Ritchie',['kinetic','crime','comedy','playful'],'criminal clockwork with bruises','🥊',3,5),
  F('Sorcerer',1977,'William Friedkin',['70s','kinetic','dark','rocket-fuel'],'four men driving nitroglycerin through hell','🚚',4,5),
  F('The French Connection',1971,'William Friedkin',['70s','kinetic','crime','gritty'],'cold-city pursuit obsession','🚇',4,4),
  F('The Taking of Pelham One Two Three',1974,'Joseph Sargent',['70s','kinetic','crime','playful'],'subway hostage snap','🚇',4,4),
  F('The Driver',1978,'Walter Hill',['70s','kinetic','crime','night-city'],'minimalist getaway cool','🚘',4,4),
  F('The Warriors',1979,'Walter Hill',['70s','kinetic','night-city','cult'],'night subway odyssey','🧱',4,4),
  F('Vanishing Point',1971,'Richard C. Sarafian',['70s','kinetic','counterculture','rocket-fuel'],'speed as existential escape','🏁',4,3),
  F('Assault on Precinct 13',1976,'John Carpenter',['70s','kinetic','dark','action'],'siege movie stripped to bone','🎯',4,4),
  F('Rolling Thunder',1977,'John Flynn',['70s','dark','angry','action'],'revenge with dead eyes','🪝',4,3),

  // psychosexual / horny / intense
  F('Eyes Wide Shut',1999,'Stanley Kubrick',['90s','psychosexual','night-city','dream','macabre'],'marital jealousy after midnight','🎭',4,4),
  F('Secretary',2002,'Steven Shainberg',['psychosexual','romantic','weird','tender'],'desire finding its grammar','✒',4,4),
  F('Y Tu Mamá También',2001,'Alfonso Cuarón',['psychosexual','romantic','tender','kinetic'],'road-trip desire and mortality','🌊',4,4),
  F('The Handmaiden',2016,'Park Chan-wook',['psychosexual','romantic','thriller','stylish'],'erotic con game blooming into freedom','🧤',4,5),
  F('Bound',1996,'Lana Wachowski, Lilly Wachowski',['90s','psychosexual','crime','romantic','stylish'],'latex-noir seduction machine','🖤',4,5),
  F('The Duke of Burgundy',2014,'Peter Strickland',['psychosexual','romantic','dream','tender'],'ritualized desire and softness','🦋',4,4),
  F('Belle de Jour',1967,'Luis Buñuel',['psychosexual','dream','dark'],'bourgeois fantasy with teeth','🔔',4,3),
  F('Betty Blue',1986,'Jean-Jacques Beineix',['psychosexual','romantic','beautiful-damage'],'love at beautiful dangerous volume','🌊',4,4),
  F('In the Realm of the Senses',1976,'Nagisa Ōshima',['psychosexual','unwatchable','dark'],'desire tightening toward oblivion','🪢',4,3),
  F('Possession',1981,'Andrzej Żuławski',['psychosexual','macabre','dream','unwatchable'],'divorce as cosmic body horror','🦑',5,4),
  F('Raw',2016,'Julia Ducournau',['body','horror','psychosexual','tender'],'coming-of-age with appetite','🥩',4,5),
  F('Titane',2021,'Julia Ducournau',['body','weird','psychosexual','tender','macabre'],'metal, flesh and impossible tenderness','🚙',4,5),
  F('Enter the Void',2009,'Gaspar Noé',['psychosexual','night-city','dream','unwatchable'],'neon death trip over Tokyo','👁',5,4),

  // unwatchable / hard watches
  F('Begotten',1989,'E. Elias Merhige',['unwatchable','underground','macabre','25th-hour','esoteric'],'creation myth dragged through ash','🩶',5,2),
  F('Satantango',1994,'Béla Tarr',['90s','unwatchable','slow','liminal'],'seven-hour rain-soaked damnation','🐄',4,2),
  F('Jeanne Dielman, 23 quai du Commerce, 1080 Bruxelles',1975,'Chantal Akerman',['unwatchable','slow','liminal'],'domestic routine becoming tectonic','🥔',4,3),
  F('Shoah',1985,'Claude Lanzmann',['unwatchable','documentary','dark'],'history faced without escape','🚂',3,2),
  F('Come and See',1985,'Elem Klimov',['unwatchable','dark','war','macabre'],'war stripping a face of childhood','🔥',4,4),
  F('Salò, or the 120 Days of Sodom',1975,'Pier Paolo Pasolini',['unwatchable','macabre','dark','esoteric'],'power rendered as degradation','⚠',3,2),
  F('Irreversible',2002,'Gaspar Noé',['unwatchable','dark','psychosexual','kinetic'],'time running backward through trauma','⏪',4,3),
  F('The Painted Bird',2019,'Václav Marhoul',['unwatchable','dark','war','macabre'],'childhood crossing a continent of cruelty','⚫',3,3),
  F('The Act of Seeing with One’s Own Eyes',1971,'Stan Brakhage',['unwatchable','documentary','macabre','underground'],'autopsy as silent confrontation','👁',4,2),
  F('On the Silver Globe',1988,'Andrzej Żuławski',['unwatchable','cosmic','esoteric','philosophical'],'unfinished cosmic scripture','🌑',5,2),

  // underground / esoteric
  F('The Holy Mountain',1973,'Alejandro Jodorowsky',['esoteric','underground','dream','philosophical','weird'],'occult pageant climbing toward the joke','🜍',5,4),
  F('El Topo',1970,'Alejandro Jodorowsky',['esoteric','underground','western','dream'],'mystic western initiation','🐇',5,3),
  F('Liquid Sky',1982,'Slava Tsukerman',['underground','cyber','psychosexual','campy','night-city'],'new-wave alien narcotic fashion','💄',5,3),
  F('Decoder',1984,'Muscha',['underground','esoteric','counterculture','night-city'],'industrial sound war against control','📻',5,2),
  F('Dr. Caligari',1989,'Stephen Sayadian',['underground','psychosexual','campy','dream'],'psychedelic therapy-room sleaze','🧿',5,3),
  F('Singapore Sling',1990,'Nikos Nikolaidis',['underground','psychosexual','macabre','dream'],'black-and-white perversion labyrinth','🖤',5,2),
  F('Funeral Parade of Roses',1969,'Toshio Matsumoto',['underground','counterculture','experimental','night-city'],'queer Tokyo exploding film language','🌹',5,4),
  F('Pink Flamingos',1972,'John Waters',['underground','campy','macabre','comedy'],'filth as competitive performance art','🦩',4,4),
  F('Desperate Living',1977,'John Waters',['underground','campy','macabre','comedy'],'fairytale trash monarchy','👑',4,4),
  F('Arrebato',1979,'Iván Zulueta',['underground','esoteric','night-city','dream'],'cinema itself as a vampire','🎞',5,3),
  F('Wax, or the Discovery of Television Among the Bees',1991,'David Blair',['90s','underground','esoteric','cyber','brainfuck'],'bees, weapons and telepathic television','🐝',5,2),
  F('The Falls',1980,'Peter Greenaway',['underground','esoteric','brainfuck','playful'],'encyclopedia of an impossible catastrophe','📚',5,2),
  F('Sombre',1998,'Philippe Grandrieux',['90s','underground','macabre','psychosexual','25th-hour'],'motion smeared into predator darkness','🌫',5,2),
  F('The Living End',1992,'Gregg Araki',['90s','underground','counterculture','romantic','angry'],'queer lovers against the road','🚘',5,3),
  F('Poison',1991,'Todd Haynes',['90s','underground','experimental','counterculture'],'three taboo genres infecting each other','☣',4,3),
  F('River of Grass',1994,'Kelly Reichardt',['90s','underground','crime','playful'],'crime movie with nowhere to go','🌴',4,3),
  F('Morvern Callar',2002,'Lynne Ramsay',['underground','tender','night-city','beautiful-damage'],'grief slipping into a new identity','🎧',5,4),
  F('Ratcatcher',1999,'Lynne Ramsay',['90s','underground','tender','dark'],'childhood beside a garbage canal','🐀',4,4),
  F('Julien Donkey-Boy',1999,'Harmony Korine',['90s','underground','beautiful-damage','unwatchable'],'family fragments on bruised video','🫧',5,2),
  F('Trash Humpers',2009,'Harmony Korine',['underground','unwatchable','weird','macabre'],'VHS goblins vandalize civilization','🗑',5,2),

  // documentaries
  F('Koyaanisqatsi',1982,'Godfrey Reggio',['documentary','philosophical','cosmic','docs-inspire'],'civilization moving like weather','🌎',5,4),
  F('Baraka',1992,'Ron Fricke',['90s','documentary','cosmic','docs-inspire'],'planetary ritual without dialogue','🌍',5,4),
  F('Samsara',2011,'Ron Fricke',['documentary','cosmic','docs-inspire'],'humanity as visual symphony','🌀',5,4),
  F('Encounters at the End of the World',2007,'Werner Herzog',['documentary','weird','docs-inspire','cosmic'],'Antarctica populated by beautiful eccentrics','🧊',5,4),
  F('Grizzly Man',2005,'Werner Herzog',['documentary','weird','docs-inspire','dark'],'obsession walking into the wild','🐻',5,4),
  F('Cave of Forgotten Dreams',2010,'Werner Herzog',['documentary','docs-inspire','philosophical','esoteric'],'prehistoric art breathing in darkness','🦬',5,4),
  F('Lessons of Darkness',1992,'Werner Herzog',['90s','documentary','cosmic','docs-inspire','macabre'],'oil-fire apocalypse filmed as another planet','🔥',5,3),
  F('Man with a Movie Camera',1929,'Dziga Vertov',['documentary','experimental','kinetic','docs-inspire'],'cinema discovering its own body','🎥',4,4),
  F('Rivers and Tides',2001,'Thomas Riedelsheimer',['documentary','harmonious','docs-inspire'],'art built to disappear back into nature','🍂',4,4),
  F('The Salt of the Earth',2014,'Wim Wenders, Juliano Ribeiro Salgado',['documentary','docs-inspire','tender'],'a photographer looking at humanity and Earth','📷',4,4),
  F('Fire of Love',2022,'Sara Dosa',['documentary','romantic','docs-inspire'],'volcanoes and a marriage inside obsession','🌋',4,5),
  F('F for Fake',1973,'Orson Welles',['documentary','weird','playful','brainfuck','docs-weird'],'truth performing a magic trick','🎩',5,4),
  F('The Act of Killing',2012,'Joshua Oppenheimer',['documentary','weird','dark','unwatchable','docs-weird'],'mass killers restage their own mythology','🎬',4,4),
  F('Gates of Heaven',1978,'Errol Morris',['documentary','weird','tender','docs-weird'],'pet cemeteries become philosophy','🐕',5,4),
  F('Vernon, Florida',1981,'Errol Morris',['documentary','weird','playful','docs-weird'],'small-town monologues from another frequency','🦃',5,4),
  F('The Emperor’s Naked Army Marches On',1987,'Kazuo Hara',['documentary','weird','angry','docs-weird'],'one veteran interrogates a nation','🎖',4,3),
  F('Tickled',2016,'David Farrier, Dylan Reeve',['documentary','weird','thriller','docs-weird'],'competitive tickling opens a trapdoor','🪶',4,4),
  F('Crumb',1994,'Terry Zwigoff',['90s','documentary','weird','dark','docs-weird'],'comic genius and family damage','✏',4,4),
  F('Tabloid',2010,'Errol Morris',['documentary','weird','playful','docs-weird'],'obsession becomes headline delirium','🗞',4,4),
  F('Winnebago Man',2009,'Ben Steinbauer',['documentary','weird','playful','docs-weird'],'viral rage meets the person behind it','📼',4,4),
  F('The Institute',2012,'Spencer McCall',['documentary','weird','esoteric','docs-weird'],'an alternate-reality game becomes a life','🗝',5,3),
  F('HyperNormalisation',2016,'Adam Curtis',['documentary','philosophical','weird','docs-weird'],'the modern world as managed unreality','📡',5,3),
  F('A Glitch in the Matrix',2021,'Rodney Ascher',['documentary','philosophical','weird','cyber','docs-weird'],'simulation belief meets internet consciousness','🐇',5,3),
  F('Hands on a Hardbody',1997,'S. R. Bindler',['90s','documentary','weird','tender','docs-weird'],'ordinary people outlast themselves for a truck','🛻',4,4),

  // tender / romantic / playful / shared friendly
  F('Before Sunrise',1995,'Richard Linklater',['90s','romantic','tender','night-city'],'two strangers walking into intimacy','🚋',5,4),
  F('Lost in Translation',2003,'Sofia Coppola',['romantic','tender','night-city','lonely'],'two lonely people in hotel light','🛗',5,4),
  F('Napoleon Dynamite',2004,'Jared Hess',['playful','tender','nostalgic','comedy','tender-weirdos'],'deadpan Idaho weirdos treated as royalty','🦙',5,5),
  F('Dead Poets Society',1989,'Peter Weir',['tender','inspiring','nostalgic'],'youth learning to want a life','🍂',4,5),
  F('The Grand Budapest Hotel',2014,'Wes Anderson',['playful','nostalgic','tender','stylish'],'melancholy confection about vanished civility','🔑',3,5),
  F('Fantastic Mr. Fox',2009,'Wes Anderson',['playful','tender','nostalgic'],'family neurosis in perfect corduroy','🦊',3,5),
  F('Moonlight',2016,'Barry Jenkins',['tender','romantic','beautiful-damage'],'identity and love in blue night','🌊',4,5),
  F('The Apartment',1960,'Billy Wilder',['romantic','tender','comedy','nostalgic'],'loneliness, compromise and one perfect key','🔑',3,5),
  F('Roman Holiday',1953,'William Wyler',['romantic','playful','nostalgic'],'a stolen day of freedom in Rome','🛵',3,5),
  F('Chungking Express',1994,'Wong Kar-wai',['90s','romantic','night-city','playful','tender'],'heartbreak moving at two speeds','🍍',5,4),
  F('Fallen Angels',1995,'Wong Kar-wai',['90s','romantic','night-city','weird','tender'],'lonely neon lives brushing past','🏍',5,4),
  F('In the Mood for Love',2000,'Wong Kar-wai',['romantic','tender','night-city','stylish'],'desire living in what is withheld','🍜',4,5),
  F('Punch-Drunk Love',2002,'Paul Thomas Anderson',['romantic','weird','tender','kinetic'],'anxiety suddenly discovering devotion','💙',5,4),
  F('Harold and Maude',1971,'Hal Ashby',['70s','romantic','playful','macabre','tender-weirdos'],'death-obsessed boy meets life-force woman','🌼',4,4),
  F('The Big Lebowski',1998,'Joel Coen',['90s','playful','comedy','cult'],'cosmic slacker detective fog','🥛',4,5),
  F('Rat Race',2001,'Jerry Zucker',['playful','comedy','kinetic'],'idiots sprinting toward money','🗺',2,5),
  F('Office Space',1999,'Mike Judge',['90s','comedy','nostalgic','counterculture'],'cubicle revolt in beige','🖨',4,5),
  F('Amadeus',1984,'Miloš Forman',['emotional','stylish','beautiful-damage'],'genius heard through envy','🎼',3,5),
  F('Requiem for a Dream',2000,'Darren Aronofsky',['dark','kinetic','beautiful-damage','unwatchable'],'desire becoming machinery','💊',3,5),
  F('Whiplash',2014,'Damien Chazelle',['kinetic','emotional','dark'],'ambition played like combat','🥁',3,5),
  F('Being John Malkovich',1999,'Spike Jonze',['90s','weird','brainfuck','playful'],'identity rented by the quarter-hour','🚪',5,5),
  F('Wild at Heart',1990,'David Lynch',['90s','romantic','kinetic','weird','macabre'],'lovers in a flaming fairy tale','🔥',5,5),

  // C-films
  F('The Room',2003,'Tommy Wiseau',['c-films','campy','comedy'],'melodrama from an alternate Earth','🥄',3,4),
  F('Fateful Findings',2013,'Neil Breen',['c-films','esoteric','campy','weird'],'laptops, destiny and government secrets','💻',4,3),
  F('Double Down',2005,'Neil Breen',['c-films','campy','weird'],'one-man spy cosmology','💿',4,2),
  F('Twisted Pair',2018,'Neil Breen',['c-films','campy','cyber','weird'],'digital twins wage incomprehensible war','🛰',4,2),
  F('Miami Connection',1987,'Richard Park, Y.K. Kim',['c-films','campy','kinetic','playful'],'taekwondo rock band versus ninjas','🥋',4,4),
  F('Samurai Cop',1991,'Amir Shervan',['90s','c-films','campy','kinetic'],'action cinema held together by confidence','⚔',4,4),
  F('Troll 2',1990,'Claudio Fragasso',['90s','c-films','campy','horror'],'vegetarian goblin catastrophe','🌽',3,4),
  F('Birdemic: Shock and Terror',2010,'James Nguyen',['c-films','campy','horror'],'clip-art birds attack romance','🦅',3,3),
  F('Hard Ticket to Hawaii',1987,'Andy Sidaris',['c-films','campy','kinetic'],'bazookas, diamonds and a toxic snake','🐍',3,4),
  F('Dangerous Men',2005,'John S. Rad',['c-films','campy','crime'],'twenty years of filmmaking resolve','🎸',4,3),
  F('Ryan’s Babe',2000,'Ray Ramayya',['c-films','campy','weird'],'a road movie continuously inventing danger','🚙',4,3),
  F('Tammy and the T-Rex',1994,'Stewart Raffill',['90s','c-films','campy','romantic'],'teen boyfriend transferred into dinosaur','🦖',4,4),
  F('Love on a Leash',2011,'Fen Tian',['c-films','campy','romantic','weird'],'a dog becomes a man for love','🐕',3,4),
  F('Champagne and Bullets',1993,'John De Hart',['90s','c-films','campy','crime'],'karaoke-noir ego monument','🥂',4,3),

  // horror/macabre/fear
  F('The Shining',1980,'Stanley Kubrick',['horror','macabre','liminal','afraid'],'a hotel slowly taking possession','🪓',4,5),
  F('Midsommar',2019,'Ari Aster',['horror','macabre','psychosexual','beautiful-damage'],'grief blooming under endless daylight','🌼',4,5),
  F('The Witch',2015,'Robert Eggers',['horror','macabre','esoteric','afraid'],'faith curdling at the forest edge','🐐',4,4),
  F('Cure',1997,'Kiyoshi Kurosawa',['90s','horror','philosophical','liminal','afraid'],'identity emptied by suggestion','❌',5,4),
  F('Pulse',2001,'Kiyoshi Kurosawa',['horror','liminal','night-city','afraid','lonely'],'the internet as loneliness after death','🖥',5,4),
  F('The Reflecting Skin',1990,'Philip Ridley',['90s','macabre','dream','tender'],'childhood myth poisoned by sunlight','🌾',5,3),
  F('The Cremator',1969,'Juraj Herz',['macabre','dark','esoteric'],'death obsession smiling politely','⚱',5,3),
  F('Angst',1983,'Gerald Kargl',['macabre','unwatchable','kinetic','dark'],'murderous compulsion in nauseating motion','🔪',4,3),
  F('Audition',1999,'Takashi Miike',['90s','horror','macabre','psychosexual','unwatchable'],'romance interview becomes a trap','🪡',4,4),
  F('Jacob’s Ladder',1990,'Adrian Lyne',['90s','horror','brainfuck','macabre'],'trauma flickering between worlds','🚇',4,4),
  F('Cemetery Man',1994,'Michele Soavi',['90s','horror','macabre','dream','playful'],'romantic zombie existentialism','⚰',5,4),
  F('The Ninth Configuration',1980,'William Peter Blatty',['philosophical','weird','dark'],'madness debating faith in a castle','🏰',5,3),

  // more taste-expanders
  F('The Man from Earth',2007,'Richard Schenkman',['philosophical','tender','low-key'],'one room, one impossible claim','🔥',5,3),
  F('There Will Be Blood',2007,'Paul Thomas Anderson',['dark','philosophical','beautiful-damage'],'ambition drilling through a soul','🛢',5,4),
  F('The Secret Life of Walter Mitty',2013,'Ben Stiller',['inspiring','tender','adventure'],'a daydreamer finally enters the frame','🏔',4,4),
  F('Into the Wild',2007,'Sean Penn',['inspiring','tender','adventure'],'freedom tested against solitude','🚌',4,4),
  F('The Rocky Horror Picture Show',1975,'Jim Sharman',['70s','campy','psychosexual','playful'],'midnight liberation in fishnets','👄',5,4),
  F('Night of the Living Dead',1968,'George A. Romero',['horror','macabre','underground'],'the modern zombie arriving through the window','🧟',5,4),
  F('Everything Everywhere All at Once',2022,'Daniel Kwan, Daniel Scheinert',['brainfuck','kinetic','tender','playful'],'multiverse chaos returning to kindness','🥯',4,5),
  F('Gummo',1997,'Harmony Korine',['90s','underground','weird','beautiful-damage'],'American debris turned into folk art','🐈',5,3),
  F('Mysterious Skin',2004,'Gregg Araki',['underground','tender','dark','beautiful-damage'],'two damaged lives orbiting the same wound','🌌',5,4),
  F('The Beach',2000,'Danny Boyle',['y2k','adventure','dark','nostalgic'],'backpacker utopia turning sour','🏝',4,3),
  F('Gattaca',1997,'Andrew Niccol',['90s','y2k','philosophical','stylish'],'human will inside genetic perfection','🧬',4,4),
  F('Dark City',1998,'Alex Proyas',['90s','brainfuck','night-city','philosophical'],'memory manipulated beneath eternal night','🌆',4,4),
  F('Open Your Eyes',1997,'Alejandro Amenábar',['90s','brainfuck','romantic','philosophical'],'desire waking inside another reality','👁',4,4),
  F('Perfect Blue',1997,'Satoshi Kon',['90s','brainfuck','horror','stylish'],'celebrity identity fracturing under the gaze','🪞',5,5),
  F('Ghost in the Shell',1995,'Mamoru Oshii',['90s','cyber','philosophical','night-city'],'consciousness floating through the network','🌐',5,5),
  F('Akira',1988,'Katsuhiro Otomo',['cyber','kinetic','night-city','body'],'teenage rage detonates a city','🏍',4,5),
  F('Paprika',2006,'Satoshi Kon',['dream','brainfuck','playful','kinetic'],'dreams breach the daytime parade','🎭',5,5),
  F('House',1977,'Nobuhiko Obayashi',['dream','horror','playful','campy'],'schoolgirl horror as candy hallucination','🏠',5,4),
  F('Santa Sangre',1989,'Alejandro Jodorowsky',['dream','macabre','esoteric','psychosexual'],'circus trauma becomes operatic nightmare','🩸',5,3),
  F('After Hours',1985,'Martin Scorsese',['night-city','kinetic','playful','elegant-panic'],'one downtown night refusing to end','🗽',4,5),
  F('Miracle Mile',1988,'Steve De Jarnatt',['night-city','end-times','kinetic','romantic'],'a phone call says the missiles are coming','☎',5,4),
  F('The Last Wave',1977,'Peter Weir',['70s','esoteric','end-times','liminal'],'apocalypse leaking through dreams','🌧',5,3),
  F('Until the End of the World',1991,'Wim Wenders',['90s','cyber','dream','philosophical','end-times'],'a globe-spanning machine for recording dreams','🌍',5,3),
  F('Safe',1995,'Todd Haynes',['90s','liminal','dark','philosophical'],'a woman becomes allergic to modern life','🧴',5,4),
  F('Naked',1993,'Mike Leigh',['90s','philosophical','dark','night-city'],'apocalyptic talk wandering London at night','🧥',5,4),
  F('The Addiction',1995,'Abel Ferrara',['90s','philosophical','horror','night-city','macabre'],'vampirism as moral hunger','🩸',5,3),
  F('Irma Vep',1996,'Olivier Assayas',['90s','stylish','playful','night-city'],'cinema culture staring at itself','🖤',4,4),
  F('High Art',1998,'Lisa Cholodenko',['90s','romantic','dark','beautiful-damage'],'downtown photography and heroin intimacy','📷',4,4),
  F('SubUrbia',1996,'Richard Linklater',['90s','counterculture','tender','beautiful-damage'],'parking-lot adulthood refusing to start','🥤',5,3),
  F('Kids',1995,'Larry Clark',['90s','underground','dark','counterculture'],'a city day with no adult guardrails','🛹',4,3),
  F('Permanent Midnight',1998,'David Veloz',['90s','dark','beautiful-damage'],'TV comedy career sinking into heroin','📺',4,3)
];

const CATEGORY_MAP = {
  '25th-hour': ['25th-hour','dream','liminal'],
  'unwatchable': ['unwatchable'],
  'c-films': ['c-films'],
  'y2k-club': ['y2k-club'],
  '90s-kinetic': ['90s','kinetic'],
  '70s-rocket': ['70s','kinetic'],
  'liminal': ['liminal'],
  'dream-logic': ['dream'],
  'rocket-fuel': ['rocket-fuel','kinetic'],
  'brainfuck': ['brainfuck'],
  'esoteric': ['esoteric','underground'],
  'docs-inspire': ['docs-inspire'],
  'docs-weird': ['docs-weird'],
  'underground-art': ['underground'],
  'night-city': ['night-city'],
  'beautiful-damage': ['beautiful-damage'],
  'tender-weirdos': ['tender-weirdos','tender','weird'],
  'end-times': ['end-times'],
  'elegant-panic': ['elegant-panic','kinetic']
};

const MOOD_MAP = {
  bored: ['kinetic','weird','playful','rocket-fuel'],
  restless: ['kinetic','rocket-fuel','elegant-panic'],
  sleepy: ['dream','liminal','25th-hour','slow'],
  horny: ['psychosexual','romantic'],
  'in-love': ['romantic','tender'],
  'weirded-out': ['weird','brainfuck','dream','esoteric'],
  homesick: ['nostalgic','tender','playful'],
  depressed: ['tender','beautiful-damage','philosophical','harmonious'],
  playful: ['playful','campy','comedy'],
  harmonious: ['harmonious','tender','liminal','documentary'],
  nostalgic: ['nostalgic','90s','y2k'],
  philosophical: ['philosophical','metaphysical','liminal'],
  curious: ['documentary','docs-weird','brainfuck','esoteric'],
  afraid: ['afraid','horror','macabre'],
  macabre: ['macabre','horror','dark'],
  wired: ['cyber','kinetic','y2k','night-city'],
  lonely: ['lonely','night-city','tender','liminal'],
  cosmic: ['cosmic','philosophical','documentary'],
  angry: ['angry','counterculture','kinetic','dark'],
  tender: ['tender','romantic','beautiful-damage'],
  campy: ['campy','c-films','playful']
};